### PR TITLE
Possible performance improvement moving componentStyle.generateAndInjectStyles out of render

### PR DESCRIPTION
**Pull request by JamieDixon**
My performance testing experience is quite limited and this is the first time I've used `react-addons-perf`.

While we were perusing the styled-components code we got to wondering about the use of `generateAndInjectStyles` in the `render` method of `StyledComponent`. Our first thought was that a side-effecty method-call probably shouldn't happen in the `render` method but rather in one of the lifecycle hooks such as `componentWillReceiveProps`, therefor keeping `render` a pure method.

I wanted to add some benchmarks to see if the change made any difference as well as trying out a few other things that might have improved performance (playing around with `shouldComponentUpdate` etc).

After putting together a benchmark based on the existing example it looks like there may be a performance improvement made by moving `generateAndInjectStyles` out of `render` and into `componentWillReceiveProps`.

Like I say, my perf experience and knowledge is very limited but I ran these stats over and over to make sure the results were consistent and it seems to be the case. It's also very likely that I'm completely missing something so bare with me on this one.

Here's some numbers from before and after the adjustment. The initial times are the first render. The next two metrics are re-renders after the container hosting the `<Example />` component gets re-rendered due to a state change.

**Before:**
 
with-code-in-render

You can see here that the inclusive render time of `Example > styled.section` (index 2) is `6.54ms` and `Example > styled.h1` (index 3) is `0.68ms`.

**After**

with-code-moved

After I moved `generateAndInjectStyles` and the other code it's reliant on, out of `render` the inclusive render time of `Example > styled.section` (index 2) has dropped to `0.32ms` and `Example > styled.h1` (index 3) is `0.04ms`.

This seems to suggest a fair performance improvement by shifting the code from `render`.

I've included the benchmark example file that I used to create these results. If I've missed something let me know and feel free to ignore this. If this is of some use then great!

### CODE REVIEW

**Comment by mxstbr** [comment]
Thank you so much for digging into this! I'm not too well-versed in the tradeoffs of this part of the codebase, but @geelen might have something to say here.

**Comment by JamieDixon** [comment]
I see from the failing tests that I did miss something so I'm having a go at solving that problem whilst retaining the perf numbers outlined.

**Comment by JamieDixon** [comment]
Ok between myself and @sheepsteak we've got the tests passing and the perf is still looking good. Let me know what feedback you have. I see the travis `danger` task is failing and that might be because we would also need to make changes to the native version also?? Cheers.

**Comment by mxstbr** [comment]
I don't see any reason not to ship this, so let's bring it up to date and ship it if @geelen hasn't said anything differently until tomorrow morning!

**Comment by JamieDixon** [comment]
Excellent! Thanks @mxstbr !

**Comment by mxstbr** [comment]
Released as `styled-components@1.0.10`, twitter announcement coming soon! So many thanks @JamieDixon!

**Pull request merged**
