### PR TITLE
Fixes for Flow v0.47.0

### PR DESCRIPTION
**Pull request by hallettj**
Thank you for taking the trouble to ship type definitions with your library! There are changes in Flow v0.47.0 that cause Flow to report errors that were not reported in previous versions. I put together this PR so that your users will not see errors when they upgrade to the latest Flow. And I made sure that type-checking still passes with Flow v0.43.1 (the version that you have been using).

As of v0.47.0 Flow strictly checks function arity. That means you will get an error if you call a function with more arguments than are listed in the function signature.  For details see https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/

There are also some changes to checking React component prop types. The latest Flow will report some errors that previous versions missed.

The full changelog is here: https://github.com/facebook/flow/blob/master/Changelog.md#0470

### CODE REVIEW

**Comment by philpl** [comment]
@styled-components/typers

**Comment by Ralf8686** [comment]
@hallettj maybe merge master and some body merge this PR?

**Comment by philpl** [comment]
@k15a can you quickly change the changelog :) the entry has landed in the wrong section now

**Comment by k15a** [comment]
Ohh thought the v2 release is older. I have created a PR.

**Pull request merged**
