### PR TITLE
Fixed ci config

### PR DESCRIPTION
**Pull request by amilajack**
- [x] Enable yarn installation and cache with appveyor for faster install times
- [x] Use clone depth of 1 for faster clone
- [x] Fast finish for faster failure reporting

### CODE REVIEW

**Comment by mxstbr** [comment]
AppVeyor fails?

**Comment by amilajack** [comment]
Looks like its failing because of `danger` (`yarn run danger run -- --verbose`). Is it required?

**Comment by mxstbr** [comment]
Yeah that's required, but should only run on Travis, not on AppVeyor.

**Comment by amilajack** [comment]
Removed `yarn run danger run -- --verbose` from appveyor config:

- [x] Enable yarn installation and cache with appveyor for faster install times
- [x] Use clone depth of 1 for faster clone
- [x] Fast finish for faster failure reporting

**Comment by amilajack** [comment]
@mxstbr Ready for merge?

**Comment by mxstbr** [comment]
This is awesome, thanks so much @amilajack! Much appreciated ✨

**Pull request merged**
