### PR TITLE
Stabilize style prop for React Native

### PR DESCRIPTION
**Pull request by jbaudanza**
This is somewhat similar to https://github.com/styled-components/styled-components/pull/3602 but I took a different take.

Since `generatedStyles` already seems stable, I just allow it to be passed directly to the `propsForElement` object.

The style prop will still be unstable in the case that the caller passes in some inline stables, but I think this should cover most use cases.

### CODE REVIEW

**Comment by probablyup** [comment]
@jbaudanza I think I'd still want this to be wrapped in a memo

**Comment by jbaudanza** [comment]
> @jbaudanza I think I'd still want this to be wrapped in a memo

OK. Would you like me to add useMemo to this PR? Or would you rather merge https://github.com/styled-components/styled-components/pull/3602? Either one would be a big help to React-native users.

**Comment by probablyup** [comment]
> > @jbaudanza I think I'd still want this to be wrapped in a memo
> 
> OK. Would you like me to add useMemo to this PR? Or would you rather merge #3602? Either one would be a big help to React-native users.

Feel free to add the `useMemo` wrapper to this PR, I generally like your change to use fewer arrays where possible 👍🏼 

Can you also add a changelog entry?

**Comment by jbaudanza** [comment]
OK! useMemo wrapper added and changelog updated. Thanks for the feedback!

**Review by probablyup — APPROVED** [review]
Thank you!

I've been a bit slow about v6 but plan on cutting an initial release during my winter break

**Pull request merged**
