### PR TITLE
fix createGlobalStyle HMR issue

### PR DESCRIPTION
**Pull request by probablyup**
I don't love this solution but it does work.

### CODE REVIEW

**Comment by probablyup** [comment]
Oh yeah probably

**Comment by probablyup** [comment]
Actually I'm not sure. There are cases where this could pop up in production like when hot rendering page transitions in next

**Comment by probablyup** [comment]
It's out...

**Comment by mhaagens** [comment]
Looks like `<GlobalStyles />` needs to be wrapped in a `styled.X` for HMR to work.
In a top level app component this doesn't work;
```
  render() {
    return (
      <>
        <h1>Hello World</h1>
        <GlobalStyle />
      </>
    );
  }
```
but this does;
```
  render() {
    return (
      <Container>
        <h1>Hello World</h1>
        <GlobalStyle />
      </Container>
    );
  }
```
So you need to wrap a styled component (or maybe just use somewhere, haven't checked) around the `<GlobalStyles />` in the top level component to get HMR working. Maybe its a React Hot Loader issue, not sure, but that solved it at least.

**Comment by probablyup** [comment]
Uhh, that should definitely not be the case.

**Comment by mhaagens** [comment]
I can share the repo with you if you want to take a look.
Definitely what happens in my app, but I might be doing something stupid heh.

**Comment by mhaagens** [comment]
@probablyup Just wondering if you had a chance to take a look?

**Comment by probablyup** [comment]
No sorry, I'm very swamped at work so I don't expect having time to look at this until the weekend

**Comment by mhaagens** [comment]
Gotcha, no worries! Thanks for helping me out 🙏

**Pull request merged**
