### PR TITLE
feat: Check dynamic creation in React 18

### PR DESCRIPTION
**Pull request by eps1lon**
Closes https://github.com/styled-components/styled-components/issues/3394
Closes https://github.com/styled-components/styled-components/issues/3409

### CODE REVIEW

**Review by probablyup — APPROVED** [review]
Thank you!

**Comment by nmoinvaz** [comment]
Since this also affects React 17, is it possible to get a new version of styled-components released? Thanks in advance.

**Comment by lynndylanhurley** [comment]
@eps1lon any possibility of getting a release for this?

**Comment by lynndylanhurley** [comment]
I realized this will be difficult to create a patch for because of the typescript conversion. I just applied this fix to the `legacy-v5` branch: #3564. Hoping it will be easier to create a `v5.3.1` release with that PR.

**Pull request merged**
