### PR TITLE
[WIP] Setup Danger to check PRs

### PR DESCRIPTION
**Pull request by nickgnd**
Hi @mxstbr, I've integrated Danger in the project: 

- Add Dangerfile with basics rules (see #95)
- Add danger command to Travis flow

I've already created a [bot](https://github.com/StylishDangerCI) and you can use this one if you want, I give you the credentials and then you can add the token in Travis ([how to](https://danger.systems/guides/getting_started.html#creating-a-bot-account-for-danger-to-use)).

### Implemented rules

- [x] Enforce CHANGELOG.md entries for each PR that touches .js files
- [x] A change was made in StyledComponent.js that wasn't made in StyledNativeComponent.js – warn that this might have to be done
- [x] Warn that changes to ThemeProvider.js, StyledComponent.js or StyledNativeComponent.js might be semver major changes if they touch the context stuff
- [x] Don't let testing shortcuts be merged into master (fit, fdescribe, it.only, describe.only)
- [x] Enforce rebases to remove "Merge master into bla" commits?
- [x] Enforce that a test must be added for the changes? (not sure if this makes sense for everything, maybe enforce for all .js files in the src/ folder except for src/vendor)
- [ ] Enforce a certain commit style? Not sure if this is really necessary.
Anything else you can come up with that might be an issue with PRs more often than not!

for this one
>  Enforce that a test must be added for the changes? (not sure if this makes sense for everything, maybe enforce for all .js files in the src/ folder except for src/vendor)

Danger print a warning like this:
"There're library changes, but not tests. That's OK as long as you're refactoring existing code."

Because, yeah you could refactoring sometimes :) What do you think?

### Extra rules

- [x] Warn for big PR (> 500 lines)
- [x] Congrats for version bump up :tada:
- [x] Warn if an external contributor (a person who is not part of the organization) changes `package.json`
- [x] Fail if PR body is missing (< 5 lines)

What do you think about these rules? Maybe too many messages can add too much noise in the PR's thread...

You can find some experiments in my [fork](https://github.com/nickgnd/styled-components/pulls), but pay attention, some of them are out of date with the current rules.

Let me know, bye  😄

### CODE REVIEW

**Comment by mxstbr** [comment]
This is amazing! I just checked out your fork and this is even better than I thought! (cc @orta)

I'll create a new bot (I want it to have a slightly different username) and get that setup on Travis asap!

**Comment by geelen** [comment]
Can we kill the rebasing stuff please? I prefer preserving git history over clean commit logs.

**Comment by mxstbr** [comment]
Yeah yeah I know @geelen, just pushing a commit to remove that.

**Comment by geelen** [comment]
Champion.

**Comment by mxstbr** [comment]
There ya go

**Comment by orta** [comment]
Looking good ❣️

**Pull request merged**
