### PR TITLE
Reflect babel-sublime updates in editor compatibility

### PR DESCRIPTION
**Pull request by amilajack**
https://github.com/babel/babel-sublime/pull/289 was merged. Updated the readme to reflect this

### CODE REVIEW

**Comment by mxstbr** [comment]
It was merged, but not released I don't think? /cc @garetmckinley @zertosh

**Comment by k15a** [comment]
@mxstbr No it's not released yet.

**Comment by zertosh** [comment]
Can someone confirm https://github.com/babel/babel-sublime/pull/289#issuecomment-277590552 ?

**Comment by mxstbr** [comment]
I can try it on a big s-c project and see if everything looks alright?

**Comment by geelen** [comment]
Any update on this? I'm doing some cleanup.

**Comment by k15a** [comment]
Still not released.

**Comment by mxstbr** [comment]
Doesn't seem like that change will be released, thanks for the PR though!

**Pull request closed without merging**
