### PR TITLE
parse css blocks to objects in attrs

### PR DESCRIPTION
**Pull request by ramitos**
related: https://github.com/styled-components/styled-components/pull/371

### CODE REVIEW

**Comment by geelen** [comment]
This is looking good, but I have a quick q (and it might just be because I'm on my phone and missed something)

Does this support passing css-as-inline-styles to anything _other_ than the `style` attr?

**Comment by ramitos** [comment]
> Does this support passing css-as-inline-styles to anything other than the `style` attr?

No, it doesn't 😕

**Comment by geelen** [comment]
Hey @ramitos I think if we can target arbitrary attributes with this it'll be good to go. Any chance you can add that?

**Comment by ramitos** [comment]
@geelen I just pushed a solution that - although not pretty - seems to work. However, I'm not comfortable with Flow enough to create a type that extends Array with a property. Any hints?

**Comment by geelen** [comment]
Closed in favour of #636.

**Pull request closed without merging**
