### PR TITLE
Update community guidelines and add core team file

### PR DESCRIPTION
**Pull request by mxstbr**
Based on the [Moya community guidelines](https://github.com/Moya/contributors) I've updated out `CONTRIBUTING.md` to explicitly explain our "Invite any contributor who has at least one PR merged" philosophy, and added a `CORE_TEAM.md` file which contains a list of core team members. (@geelen, @mxstbr, @philpl, @schwers; in order of addition)

I've also already set up an instance of [Aeryn](https://github.com/Moya/Aeryn), which will automatically invite any collaborator that has a PR merged into the main `styled-components` repo to the organisation and give them commit access.

I hope that (as with Moya) this makes the `styled-components` project longer lasting and removes the core team members as bottlenecks from the evolution of the library.

/cc @orta @alloy who are the source of inspiration (and of the code!) behind this change, thank you!

### CODE REVIEW

**Comment by mxstbr** [comment]
@philpl did some more small updates, but this should now really be ready to go! Please ship since Aeryn is already deployed—so we're already inviting all the folks haha :laughing:

**Comment by maciej-ka** [comment]
I just got confused by this Member status. Because it's a dream thing, the night I got it was really without a sleep, I felt very obliged to give a lot to project and, shit, I wrote about all this on my company slack. 

Please, reconsider. There is a dedicated "Contributor" status for user after merge. Spare this bi-polar trip to your community.

Now: where is the hole I can dig myself before company Monday daily?

**Comment by philpl** [comment]
@maciej-ka for all intents and purposes it’s a “trial” for now. So we’ll see how people will react to it.

For us it means that more contributors can step up and take over temporarily when we’re busy, which has been an issue lately. It also shifts perceived responsibilities tremendously. We’re just as much volunteers as core contributors as you are as a contributor.

Personally, I feel that it’s the intended outcome that you feel you share some responsibility now, but I’m sorry if you lost some sleep over it ;) we’re always available via DMs (and all else) to discuss issues that come to mind.

Let’s see how this pans out. It’s a shame that we can’t assign “custom badges” to people. I’d love to change Github’s default terms

**Comment by morajabi** [comment]
> I suspect that this is generally confusing, @morajabi got the situation just as wrong as I did.

Sorry, I don't get what are you talking about! 🙌

**Comment by mxstbr** [comment]
@maciej-ka you weren't automatically invited, I invited you because your work is awesome! :blush: I just now set up the autoinvite thing. Same for @morajabi.

**Comment by morajabi** [comment]
@mxstbr Of course, I knew it wasn't automatic, I still kept the pic of the invite 😊  @SaraVieira 
image

**Comment by GGAlanSmithee** [comment]
Thanks for the invite @mxstbr, will try to contribute in a meaningful way.

It's actually a very intereseting approach, that makes a lot of sense in OSS. I wouldn't be surprised if it has the exact intended affect that @philpl states, a feeling of responsibility. That's the first feeling I got anyway. I wonder why more projects haven't taken this approach earlier. Will be interesting too see the consequences of this.

**Comment by mxstbr** [comment]
@GGAlanSmithee yeah the past few months have shown that it's sustainable for us three to be the only ones with merge control, we turned out to be a huge bottleneck.

Let's see what happens now!

**Comment by morajabi** [comment]
@mxstbr It was always my question what are "Core Team members"! Thanks for this

**Pull request merged**
