### PR TITLE
Changed duplicate comment

### PR DESCRIPTION
**Pull request by tiemevanveen**
See change.

Or was that intentional?

### CODE REVIEW

**Comment by mxstbr** [comment]
Not sure why it shouldn't be that way – what this CSS does it is truncates the text content of the container at the width of the container and adds an ellipsis?

**Comment by tiemevanveen** [comment]
Okay, I the comment form [line 80](https://github.com/styled-components/styled-components/blame/master/docs/tips-and-tricks.md#L80) might have been accidentally copied over to [line 125](https://github.com/styled-components/styled-components/blame/master/docs/tips-and-tricks.md#L125) :)

**Comment by mxstbr** [comment]
Ah no, sorry, you're right! I didn't properly look at the context, you're absolutely right, my bad!

**Comment by mxstbr** [comment]
Thank you for catching that!

**Comment by tiemevanveen** [comment]
> Ah no, sorry, you're right! I didn't properly look at the context, you're absolutely right, my bad!

Haha. No worries 👍  😃

**Comment by mxstbr** [comment]
Thanks again!

**Pull request merged**
