### PR TITLE
Extract DOM shorthands into a separate file

### PR DESCRIPTION
**Pull request by philpl**
A really, *really* simple PR that extracts the DOM shorthands to a separate file for readability :)

I definitely want to get more into styled-components development, since I'm totally stoked by #59. I was even considering starting my own styling library for getting a babel transform for styling working, but I'm really into styled-components, so I'd love to help out here :)

### CODE REVIEW

**Comment by mxstbr** [comment]
This is a great change, but a bit dependent on how #166 plays out. If we decide to go the proxy route we won't merge this, but if we don't I'll definitely land this!

Thanks for taking the time to do this refactor, appreciated!

(Also, any help with the babel transform would also be much appreciated)

**Comment by philpl** [comment]
@mxstbr Cheers for the quick reply :)

For what it's worth, pushing the proxy overhead to the user sounds like it could frustrate a lot of people. I don't see why `styled('unsupported-element')` would be bad in any way.
These are after all just shortcuts ;)

**Comment by mxstbr** [comment]
The proxy polyfill is 30 lines of code, so that's even less than all of our helpers, plus it allows you to use whatever custom element you want! 🎉

I'm going to close this in favor of #166, thank you so much for taking the time to contribute!

**Comment by mxstbr** [comment]
So as it turns out, we're not going to merge #166 after all, so I'm reopening this PR! Let's get this landed!

**Comment by mxstbr** [comment]
@styled-components/typers this broke flow, as now `styled.div`, `styled.a`,... are dynamically defined, so flow complains that `styled.x` is undefined. Any ideas how we can fix that?

**Comment by relekang** [comment]
@mxstbr Looks like it works with adding `// @flow` to the domElements file. PR coming up 🙂

**Comment by mxstbr** [comment]
Oh man, how'd I miss that! Ugh.

**Comment by philpl** [comment]
Sorry for not being active on this :) have yet to stay on top of my Github notifications ^^

**Pull request merged**
