### PR TITLE
Provide GitHub Badge in readme

### PR DESCRIPTION
**Pull request by iRoachie**
Example code that maintainers can add to their readme to show off styled-components!

### CODE REVIEW

**Comment by mxstbr** [comment]
I played around a bit more with shields.io, what do you think of this? https://img.shields.io/badge/style-%F0%9F%92%85%20styled--components-orange.svg?colorB=daa357&colorA=db748e



A bit more on brand, /cc @philpl might want to take a crack too

**Comment by philpl** [comment]
@mxstbr super happy with your badge! Totally on brand in terms of colours and emoji! Also, this is a great idea :)

**Comment by iRoachie** [comment]
This looks great actually. Should I change the PR?

**Comment by mxstbr** [comment]
@iRoachie that'd be awesome!

**Comment by morajabi** [comment]
@mxstbr @philpl The emoji not clear tho, also it will suck on Windows or Ubuntu :)

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Pull request merged**
