### PR TITLE
peer dependency & globals adjustments for bundle size

### PR DESCRIPTION
**Pull request by probablyup**
Brings our bundle size down to ~14.2 kB

### CODE REVIEW

**Comment by probablyup** [comment]
@kitten any comments on this one?

**Comment by mxstbr** [comment]
If I understand this correctly, this will mean people have to `npm install --save prop-types styled-components` to make styled-components work? That doesn't seem very ideal given that prop-types for styled components are basically useless, I'd much rather remove them?

**Comment by probablyup** [comment]
@mxstbr like remove them entirely? wouldn't that be sad for dev feedback?

**Comment by mxstbr** [comment]
I have never seen a proptype error from a styled component. Our factory functions make it pretty much impossible to mess them up?!

**Comment by kitten** [comment]
I'd say our Prop Types aren't really that useful anymore but if we want to keep them we can also move the package back to dependencies and exclude it from the bundle manually in our config

**Comment by probablyup** [comment]
That works, will make the change

**Pull request merged**
