### PR TITLE
add onReset to valid react props list

### PR DESCRIPTION
**Pull request by 4urbanoff**
Hello! This prop needed for form tag

### CODE REVIEW

**Comment by philpl** [comment]
@4urbanoff Cheers! Nice spot!

Could you add an entry to the changelog please?

**Comment by 4urbanoff** [comment]
@philpl completed!)

**Comment by philpl** [comment]
Thanks a lot for the change! I'll merge it once the checks pass :wink:

#1234 what a lucky number :tada:

**Comment by philpl** [comment]
Thanks a lot for fixing this :tada:

**Comment by 4urbanoff** [comment]
And thank you! Styled forever! ))

**Pull request merged**
