### PR TITLE
Added reference to styled-components-theme lib

### PR DESCRIPTION
**Pull request by erikras**
I find it very useful. But then I'm biased. 😆

### CODE REVIEW

**Comment by k15a** [comment]
Could you please move this to the end of the helpers list to be fair to others?

**Comment by erikras** [comment]
I was going by alphabetical order.

**Comment by erikras** [comment]
Also, my lib predates all the other "Helpers". But okay...

**Comment by k15a** [comment]
We always handled it this way so it's just fair :)

**Comment by k15a** [comment]
There is also https://github.com/romellogood/awesome-styled-components if you want to submit have your library on another list as well.

**Pull request merged**
