### PR TITLE
Tiny common helpers

### PR DESCRIPTION
**Pull request by JoshRosenstein**
Just created isFunction in utils (removed the one in model/themeprovider) ,added isDev to constants, adjusted isObjectLiteral to handle null, removed redundancies and fixed the flowfixme issues where %check was missing or not working correctly. I could not run any tests though, it wasnt compiling for me and i didnt want to start poking around config, so i stopped at this point and i'll see if Travis tells me if i broke anything =/

### CODE REVIEW

**Comment by probablyup** [comment]
Thanks! Could you switch the base branch to “develop”? We aren’t accepting any more PRs for 3.0 now that we’re in the home stretch for 4.0 🙃

**Comment by JoshRosenstein** [comment]
NP, do i need to do anything to resolve the conflicts ?

**Comment by probablyup** [comment]
Yeah you'll have to rebase against develop

**Comment by JoshRosenstein** [comment]
Closing, will create a new PR in the future

**Pull request closed without merging**
