### PR TITLE
[WIP/Exploration] Hooks

### PR DESCRIPTION
**Pull request by alexandernanberg**
Some early exploration of react hooks 

Related #2342

### CODE REVIEW

**Comment by alexandernanberg** [comment]
Absolutely – once I get the sandbox working with these changes 😬 Right now I get this error `Hooks can only be called inside the body of a function component.` when trying to SSR, will investigate further!

**Comment by mxstbr** [comment]
Maybe they aren't supported in SSR?

**Comment by alexandernanberg** [comment]
I'm pretty certain they are 100% supported in SSR, could be a bug in their end or something weird we're doing... hooks works fine in `ThemeProvider` but not in `StyleSheetProvider` for some reason

**Comment by gaearon** [comment]
You probably have two Reacts in node modules.

**Comment by alexandernanberg** [comment]
Ah I finally figured out how to fix the sandbox error! I think there are some issues when symlinking the react dependency (like with lerna), but in this case it was possible to solve with a webpack alias.

**Comment by alexandernanberg** [comment]
@mxstbr I was able to get some screenshots now 😏 

Before (the entire Hero component won't even fit on my screen 😅 )
image

After 😍 
image

**Comment by mxstbr** [comment]
Amazing 😍😍😍

**Comment by Jessidhia** [comment]
If the `StyledComponent` class is itself ported to being a `forwardRef` body component, this could become even shallower :fire:

**Comment by probablyup** [comment]
@alexandernanberg excellent work! have you had a chance to look at the test failures?

**Comment by alexandernanberg** [comment]
@probablyup Thanks! Yeah but I've been unable to come up with a solution... there seems to be an issue with `jest.resetModules()` that causes react to throw the `Hooks can only be called inside the body of a function component.` error. 

I tried with Jest's `moduleNameMapper` as suggested in [this comment](https://github.com/facebook/react/issues/13991#issuecomment-463486871) but that didn't work either 🤔

**Comment by Jessidhia** [comment]
I did solve it in my PR (#2390) but it's not very pretty. It's something to do with how `react` communicates with its reconciler.

**Comment by alexandernanberg** [comment]
Ah nice, copied that fix here as well!

**Comment by alexandernanberg** [comment]
I'm going to close this since #2390 supersedes it and has a better implementation 🎉

**Pull request closed without merging**
