### PR TITLE
Add other solutions section

### PR DESCRIPTION
**Pull request by kentcdodds**
I put a section like this on all my repositories because I think it's pretty handy for people trying to make a decision about what solution fits their use cases and preferences best.

### CODE REVIEW

**Comment by k15a** [comment]
A simple question aside. What's the benefit of a review request? Is there a special page where I can see all PR I got requested to review? This would be really handy. But as far as I know it's only another notification isn't it?

**Comment by kentcdodds** [comment]
> as far as I know it's only another notification

That's me as well :man_shrugging:

**Comment by existentialism** [comment]
There's https://github.com/pulls/review-requested

**Comment by nerdchacha** [comment]
Also, here
image

**Comment by kentcdodds** [comment]
ping?

**Pull request merged**
