### PR TITLE
Parse CSS blocks to objects in attrs

### PR DESCRIPTION
**Pull request by ramitos**
based on #371

cc/ @geelen

### CODE REVIEW

**Comment by ramitos** [comment]
I'll close this because this wont work with the new v2 parser. I'll try to make it work with a rebased `attrs` branch

**Comment by geelen** [comment]
Ah yep sorry about that @ramitos you'll need to work off `v2`. Sadly, that makes this task a bit more difficult, since I don't know that you have access to the parse tree like you do with postcss. Good luck!

**Comment by ramitos** [comment]
@geelen yeah, but I'm hopeful that this is still achievable 😉 hopefully I don't run into some weird edge case!

**Comment by ramitos** [comment]
@geelen I have a branch with [`attrs`](https://github.com/styled-components/styled-components/tree/attrs) with rebased [`v2`](https://github.com/styled-components/styled-components/tree/v2):  https://github.com/styled-components/styled-components/compare/v2...ramitos:attrs-with-style

As you can see it is a clean merge to [`v2`](https://github.com/styled-components/styled-components/tree/v2), but it can't be automatically merged with [`attrs`](https://github.com/styled-components/styled-components/tree/attrs) or [`css-in-attrs`](https://github.com/styled-components/styled-components/tree/css-in-attrs). I don't want to submit a new PR to  [`v2`](https://github.com/styled-components/styled-components/tree/v2) so that #365 is not lost.

Feel free to either suggest the best approach, or just use the commits in your #365 😉

**Comment by geelen** [comment]
Awesome, I'll take a look tonight hopefully!

**Comment by ramitos** [comment]
@geelen any update on the validity of the solution?

**Comment by geelen** [comment]
Not yet but I have merged #365 into `v2` so can you submit a PR against that?

**Comment by ramitos** [comment]
@geelen thanks, just did 😉

**Pull request closed without merging**
