### PR TITLE
add cache in SSR class

### LINKED ISSUE #378: Server side rendering breaks if you after styleSheet.reset()
## Version

v2 branch in github

## Reproduction

```js
import React from 'react';
import {renderToString} from 'react-dom/server';
import styled, {styleSheet} from 'styled-components';

const Heading = styled.h1`
  color: red;
`;

renderToString(<Heading>Hello World</Heading>);

console.log('run 1:')
console.dir(styleSheet.getCSS());

styleSheet.reset();

renderToString(<Heading>Hello World</Heading>);

console.log('run 2:');
console.dir(styleSheet.getCSS());
```

Outputs:

```
run 1:
'.styled-components-bug__Heading-ecpbxy {}\n.kDmCMo { color: red; }'
run 2:
''
```

## Steps to reproduce

Attempt to render a component server side by resetting the style sheet, rendering it, then getting the css.

## Expected Behavior

You should get the same css every time you render.

## Actual Behavior

After resetting, you get empty css.

### PR DESCRIPTION
**Pull request by thisguychris**
- fixes #378 
- I've added cache in the SSR instance itself, it seems more manageable there

### CODE REVIEW

**Comment by thisguychris** [comment]
@geelen / @mxstbr just one failing test here, how do I test for reset()? if getcss() will always get the cached version of the css?

**Comment by thisguychris** [comment]
@mxstbr kinda wrapping my head for, if we're caching the CSS, what do we need reset() for?

**Comment by wmertens** [comment]
How about just removing that cache? Was it really necessary @geelen?

**Comment by philpl** [comment]
I think this is not necessary anymore after @geelen's rewrite of the stylesheet / ssr logic

**Comment by philpl** [comment]
Closed since the entire StyleSheet / SSR logic changed

**Pull request closed without merging**
