### PR TITLE
Fix statement on Ukraine

### PR DESCRIPTION
**Pull request by Fer0x**
Being a native ukrainian/russian speaker, want to fix some automatic translation issues. 
Also, can I adopt it for v6 version?

### CODE REVIEW

**Review by probablyup — APPROVED** [review]
Thank you, and yes feel free to make a v6 version

**Comment by AuthorProxy** [comment]
Clowns everywhere :D I hope I will see any messages from US patriots about Iraq, Livia or Syria @probablyup

**Comment by naghtigal** [comment]
> Clowns everywhere :D I hope I will see any messages from US patriots about Iraq, Livia or Syria. @probablyup

What with your face, clown? Are you already mobilized or hiding somewhere in Kazakhstan?

**Comment by teamquatro** [comment]
> Clowns everywhere :D I hope I will see any messages from US patriots about Iraq, Livia or Syria. @probablyup

Have you already chosen where you will hide from mobilization? Maybe Georgia, Kazakhstan or Mongolia? Unless, of course, the military commissariat will let you do it ..

**Comment by AuthorProxy** [comment]
I am not you lol, hiding from Ukraine mobilization, I am cleaning my ak47, named it "Svinorez"

**Comment by naghtigal** [comment]
> I am not like you lol, "hiding from Ukraine mobilization", I am polishing my ak47 - named it "Svinorez"

Be careful kid, don't shut your testicles accidentally coz your "svinorez" might want to punish some "svinosobaka"

**Pull request merged**
