### PR TITLE
[Proposal] Replace .attrs with .withProps constructor

### PR DESCRIPTION
**Pull request by philpl**

### CODE REVIEW

**Comment by geelen** [comment]
Any reason this is against `v2-rc` and not `v2`?

**Comment by philpl** [comment]
@geelen Can't remember. I think because I was just on that branch and didn't think about it :wink:

**Comment by mxstbr** [comment]
Do we want this?

**Comment by philpl** [comment]
@mxstbr Nah, we're going with the namespace solution, so this is just another way of using `.attrs` to solve the problem that namespaces will solve for us.

**Pull request closed without merging**
