### PR TITLE
allow attrs to be called with a function

### PR DESCRIPTION
**Pull request by probablyup**
attrs is now implemented as an array internally to make it
easier to do merging etc and handle different types of things
passed in

Closes #1171 

This is an alternate implementation of https://github.com/styled-components/styled-components/pull/2176 that will allow more & easier customization in the future (and is smaller.)

### CODE REVIEW

**Comment by imbhargav5** [comment]
This is so amazing. :D Also, love the "probably a bad idea" test cases.

**Comment by probablyup** [comment]
Haha I can't take credit for those tests!

**Comment by probablyup** [comment]
mmk this is ready to go

**Comment by imbhargav5** [comment]
:fire:

**Pull request merged**
