### PR TITLE
test: jest 20, switch ssr tests to snapshots and use node environment

### PR DESCRIPTION
**Pull request by probablyup**
See commits

### CODE REVIEW

**Comment by philpl** [comment]
Nice! @geelen should probably take a look, but he's been kind of busy. But since this is not actually changing any logic or test semantics it should be fine.

cc @mxstbr any additional thoughts?

**Comment by philpl** [comment]
@mxstbr I don't see a reason why we shouldn't switch to this :smile:

@probablyup Can you add a changelog entry so we can merge this?

**Comment by probablyup** [comment]
@philpl yup, probably tonight or tomorrow

**Comment by probablyup** [comment]
@philpl done

**Comment by philpl** [comment]
cheers! :)

**Pull request merged**
