### PR TITLE
Update inline-style-prefixer to the latest version

### PR DESCRIPTION
**Pull request by rofrischmann**
Updating the prefixer to the latest version basically improves prefixing performance by 4-5x
Definitely something you should consider here!

Drawback:
We updated the browser support versions which might change the prefixing behavior. You can create a custom prefixer instance to solve that - let me know and I update the PR.

### CODE REVIEW

**Comment by k15a** [comment]
We don't use inline-style-prefixer anymore because stylis is automatically prefixing for us. Don't know why we still have inline-style-prefixer in the package.json. @philpl any idea?

**Comment by philpl** [comment]
Oh, sorry! @k15a is correct, we're not using it anymore, and there's some dead code left over from it.

**Comment by rofrischmann** [comment]
Ah I see. Was wondering why it was still in the package.json and included in the autoprefix util.

**Comment by philpl** [comment]
Opened a PR to fix this: https://github.com/styled-components/styled-components/pull/881

@rofrischmann We had some dead code while we migrated to v2, and some of it wasn't deleted it seems :/ I'm not really sure why we didn't pick up earlier on that

**Pull request closed without merging**
