### PR TITLE
Ignore comments in InlineStyle

### PR DESCRIPTION
**Pull request by ckknight**

### CODE REVIEW

**Comment by philpl** [comment]
Hiya, sorry for not following up on this earlier.

Can you please add an entry to the Changelog? This way I also won't have to pull and test this manually 😅 

Can you also please add a test for comments to the native tests so that we won't have another regression? https://github.com/styled-components/styled-components/blob/master/src/native/test/native.test.js

**Comment by ckknight** [comment]
@philpl Ball's back in your court. 🏀

**Comment by philpl** [comment]
Seems to be working as intended! 👍

**Comment by philpl** [comment]
Cheers, sorry that it took so long :)

**Pull request merged**
