### PR TITLE
Flow

### LINKED ISSUE #51: Stricter typings
We need to tighten our flow typings. People will probably (even if we don't explicitly export them) start using them in their code, and it might break stuff.

### PR DESCRIPTION
**Pull request by ryyppy**
Adds strict typings for styled-components @relekang 

Closes #51

### CODE REVIEW

**Comment by ryyppy** [comment]
@mxstbr What's wrong here?

**Comment by mxstbr** [comment]
This somehow broke CI `¯\_(ツ)_/¯` Can you try force-pushing the branch again?

**Comment by mxstbr** [comment]
Can you resolve the merge conflicts? Then CI will kick in!

**Comment by relekang** [comment]
Rebased it, need to figure out some new flow errors. 

I am not sure what we want to do with the `AbstractStyledComponent`?

**Comment by mxstbr** [comment]
> I am not sure what we want to do with the AbstractStyledComponent?

What do we need to do with it? For reference, we need it to check inheritance.

**Comment by mxstbr** [comment]
Some ESLint errors appeared now, would you mind fixing those and updating the CHANGELOG?

**Comment by relekang** [comment]
> What do we need to do with it? For reference, we need it to check inheritance.

Decide how much should be in it. As for now, I put as little as I could in it.

> Some ESLint errors appeared now, would you mind fixing those and updating the CHANGELOG?
Done ✌️

**Comment by mxstbr** [comment]
Awesome, thank you so much!

**Comment by msmfsd** [comment]
Guys love styled-components so thanks!
Am on v1.0.10 and still getting flow-type errors. Note I am using create-react-app and my flow config is:
```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*
```
Here are the errors:
```
node_modules/styled-components/src/models/InlineStyle.js:3
  3: import camelizeStyleName from 'fbjs/lib/camelizeStyleName'
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/camelizeStyleName. Required module not found

node_modules/styled-components/src/models/InlineStyle.js:5
  5: import { StyleSheet } from 'react-native'
                                ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/native/index.js:4
  4: import reactNative from 'react-native'
                             ^^^^^^^^^^^^^^ react-native. Required module not found

node_modules/styled-components/src/utils/flatten.js:2
  2: import hyphenate from 'fbjs/lib/hyphenateStyleName'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ fbjs/lib/hyphenateStyleName. Required module not found
```

**Comment by ron-liu** [comment]
I love styled-components too, thanks guys. 
But I still get the flow-type error as below:
```
node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ number. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ string. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type
```

My flow config file is below:
```
[ignore]
.*/react-side-effect/.*
.*/config-chain/.*
.*/styled-components/src/.*

[include]

[libs]
flow-typed
node_modules/styled-components/flow-typed/react-native.js
node_modules/styled-components/flow-typed/glamor_vx.x.x.js
node_modules/styled-components/flow-typed/lodash_v4.x.x.js
node_modules/styled-components/flow-typed/inline-style-prefixer_vx.x.x.js

[options]
esproposal.decorators=ignore

```

**Comment by relekang** [comment]
These errors will be fixed by #334

**Pull request merged**
