### PR TITLE
Fix defaultProps used instead ThemeProvider after initial render

### LINKED ISSUE #445: StyledComponent uses defaultProps for theme instead of theme provided by ThemeProvider after initial render
## Version
1.4.2

## Reproduction
http://www.webpackbin.com/4Jdl6JjwM

## Steps to reproduce

Click the button at least once and the click count text will turn from blue (the given value for `theme.color`) to red (the default prop for `theme.color`).

## Expected Behavior

`StyledComponent`s that are children of `ThemeProvider` should always use the provided `props.theme` instead of `defaultProps.theme`.

## Actual Behavior

On initial render `props.theme` is correct, every subsequent render `props.theme` is `defaultProps.theme`.

### PR DESCRIPTION
**Pull request by k15a**
Closes #445

### CODE REVIEW

**Comment by k15a** [comment]
@chadwatson Could you check out if this is working for you?

**Comment by chadwatson** [comment]
Sure thing. Give me a few minutes.

**Comment by chadwatson** [comment]
Yes, that fixes the problem! It is still double rendering the child styled component though. Is that a problem?

**Comment by k15a** [comment]
It's double rendering because you're passing a new object every time and ThemeProvider is checking the reference. In your example they are different so ThemeProvider thinks it is a new Theme.

**Comment by k15a** [comment]
@diegohaz Do you how chadwatsons example is different than the test you introduced in [#345](https://github.com/styled-components/styled-components/pull/345/files#diff-e9e543c50e5cefa6f2c6469f6abccc5b)? I am not seeing any difference.

**Comment by diegohaz** [comment]
@k15a The difference is that he uses `setState` after the first render, right?

**Comment by xcoderzach** [comment]
@k15a I think it's because the props change, in this specific case, it's the `children` prop (the count).

**Comment by xcoderzach** [comment]
Any time the props on the styled component change without re-mounting this should happen.

**Comment by xcoderzach** [comment]
Probably something fix to do after this gets landed, but it feels a bit precarious to have this same logic duplicated 4x. 😬

**Comment by k15a** [comment]
@xcoderzach I wasn't thinking of the children prop. Added tests now.

**Comment by k15a** [comment]
> Probably something to fix after this gets landed, but it feels a bit precarious to have this same logic duplicated 4x. 😬

Basically the whole StyledNativeComponent.js is a duplicate of StyledComponent.js. But it feels wrong anyway^^

**Comment by diegohaz** [comment]
@k15a Can you confirm if that test fails without the changes on this PR?

**Comment by k15a** [comment]
Yeah it's failing without the changes.

**Pull request merged**
