### PR TITLE
Add ReactNative example

### PR DESCRIPTION
**Pull request by mxstbr**
This will make ReactNative development so much easier!

Now, to develop for ReactNative all you have to do is go into the `example/native/` folder, run `npm start` in one process and `npm run ios` in the other. 👌 All the changes you make in `styled-components` core will be directly reflected, which is so awesome!

Huge props to @grabbou and @cem2ran for helping out, otherwise I would've given up.

/cc @geelen you'll love this

### CODE REVIEW

**Comment by cem2ran** [comment]
As mentioned in https://github.com/styled-components/styled-components/pull/250 I locked down the react version. This should be fixed before merging? https://github.com/styled-components/styled-components/pull/259/commits/603110bd7167531ceae3755b07b3cac9c1c54504#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R78

**Comment by mxstbr** [comment]
Ah damn, did I get rid of that? I thought I kept that when I merged your PR?

**Comment by cem2ran** [comment]
Nope. I just mean when you merge into master. Actually ~ would have sufficed. The issue is with the minor release 15.4. I wasn't able to figure out the problem.

**Comment by cem2ran** [comment]
Appears to be the following issue: http://stackoverflow.com/a/40737409/1066356

**Comment by cem2ran** [comment]
Alright, it's working now! https://github.com/styled-components/styled-components/compare/react-native-example...cem2ran:react-native-example

I added the Android entry file as it also works on Android.

`latest` preset results in a runtime TypeError. I removed this and also `flow-react-proptypes` plugin as it otherwise makes the packager throw:
```
SyntaxError: Unexpected token, expected , (193:260)
    at Parser.pp$5.raise (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp.expect (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:1615:33)
    at Parser.pp$2.parseBindingList (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:2934:12)
    at Parser.pp$1.parseFunctionParams (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:2260:22)
    at Parser.pp$1.parseFunction (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:2250:8)
    at Parser.pp$3.parseFunctionExpression (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:3596:17)
    at Parser.pp$3.parseExprAtom (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:3558:19)
    at Parser.pp$3.parseExprSubscripts (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/Users/cem2ran/git/styled-components/node_modules/babylon/lib/index.js:3311:19)
```

Might be interfering with the plugins added by the react-native preset: https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/44

The project builds successfully, but the following tests are failing:
```
jsdom tests
    1) "before all" hook for "should inject only once for a styled component, no matter how often it's mounted"

css features
    2) should add vendor prefixes in the right order
    3) should add vendor prefixes for display
```

**Comment by mxstbr** [comment]
Getting an error when running `npm start` suddenly, some weird syntax parsing error! Any ideas what's up with that @cem2ran?

**Comment by cem2ran** [comment]
As mentioned in https://github.com/styled-components/styled-components/pull/259#issuecomment-263079172 the issue is related to the 'flow-react-proptypes' plugin. If you remove this and 'latest' preset then it should work:

```
{
  "presets": [
    "react",
    "react-native"
  ],
  "plugins": [
    "add-module-exports",
    "transform-flow-strip-types",
    "transform-object-rest-spread",
    "transform-class-properties"
  ]
}
```

**Comment by mxstbr** [comment]
> `flow-react-proptypes`

We want that plugin though 😢

**Comment by mxstbr** [comment]
Upstream issue at `flow-react-proptypes`: https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/62

**Comment by philpl** [comment]
@mxstbr This seems to have been fixed: https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/62#issuecomment-295422749

**Comment by mxstbr** [comment]
Since we have tests for ReactNative now this seems unnecessary, going to close it out.

**Pull request closed without merging**
