### PR TITLE
Fix react-router v4

### LINKED ISSUE #75: Styled-components break with react-router v4
Trying to make use of a styled-component with react-router v4 breaks with the following error

    StyledComponent.js:71 Uncaught TypeError: subscribe is not a function
    componentWillMount @ StyledComponent.js:71

Confirmed that this isn't an issue with react-router because
This works

    const Li = props => <li style={{display: "inline-block"}} {...props}/>

But this fails and throws the above error when used with react-router v4

    const Li = styled.li`
    display: inline-block`

### PR DESCRIPTION
**Pull request by mxstbr**
react-router uses react-broadcast to handle context updates. We do too,
except I inlined the implementation to avoid multiple wrapper
components. That would totally be fine, except I also slightly adapted
the implementation – and that broke anything else using react-broadcast,
including react-router v4.

This PR fixes that by instead attaching our theme to this.context
directly, not to this.context.broadcasts. This avoids overlap and fixes
the bug. (manually verified)

Closes #75

### CODE REVIEW

**Comment by sheepsteak** [comment]
👍 LGTM

**Comment by gbozee** [comment]
:+1:

**Comment by madeinfree** [comment]
👍🏻

**Comment by mxstbr** [comment]
Awesome, thanks for testing everyone! Publishing a new version now!

**Pull request merged**
