### PR TITLE
Add some files to .npmignore

### PR DESCRIPTION
**Pull request by YasserKaddour**
I would add CONTRIBUTING.md and CODE_OF_CONDUCT.md, but it's your call.

### CODE REVIEW

**Comment by YasserKaddour** [comment]
Since  CONTRIBUTING.md and CODE_OF_CONDUCT.md where only added 3 days ago, I will go ahead and add them.

**Comment by philpl** [comment]
Both aren't necessary, so this looks good to me, but do we want to use the explicit "files" list in package.json instead maybe? CC @mxstbr

**Comment by YasserKaddour** [comment]
I think explicit "files" would be better, If that's OK with you I will do that instead.

**Comment by YasserKaddour** [comment]
Also, from what I could see in other packages `docs`, `flow-typed` and `src` folders should get the axe, a let only `dist` and `lib` remain.

**Comment by geelen** [comment]
Keep the src folder! It's such a pain when you're using libraries and you
only have transpired source to read through without jumping to GitHub. Same
goes for docs, next time you're hacking without internet you'll thank me :)

**Comment by philpl** [comment]
Agreed! :smile: Keep all three

**Comment by YasserKaddour** [comment]
@geelen You're right, I will make another PR tomorrow.

**Pull request closed without merging**
