### PR TITLE
Explain how to use v2

### PR DESCRIPTION
**Pull request by wmertens**

### CODE REVIEW

**Comment by mxstbr** [comment]
I'm not sure this is worth putting in the README, as it'll be out soon anyway and it's currently too buggy (see #433) to tell everybody to use.

Let's leave this open until we've tried it internally on a few projects so we can find the gravest bugs. (like #433)

**Comment by axelson** [comment]
@mxstbr is there a place to collect feedback about v2? I've used in on a small simple internal project and it appears to be working great.

**Comment by GGAlanSmithee** [comment]
I am also using v2 with ssr and it's working great so far (with the exception of the babel transform, which made react re-render server -> client)

**Comment by mxstbr** [comment]
> @mxstbr is there a place to collect feedback about v2?
> I am also using v2 with ssr and it's working great so far

Good idea, just opened #453, please comment!

**Comment by garetmckinley** [comment]
Is there anything written that explains whats new/different in 2.0? I couldn't find release notes

**Comment by k15a** [comment]
@garetmckinley The main differences are a new parser #286 and classnames are now based on a per component basis #227 which gives you support for a component selector #142. It's a major update because the new parser and classnames could potentially break styled-components for some users.

**Comment by kopax** [comment]
> could potentially break styled-components for some users
@k15a Could you elaborate a bit please ? I am experiencing issue with the V2 and I have no clue. #453

**Comment by philpl** [comment]
We're tracking v2 as a GH milestone here: https://github.com/styled-components/styled-components/milestone/5

It should be out soon. And by soon, this time we mean **soon** 😆

**Pull request closed without merging**
