### PR TITLE
Improve example app

### LINKED ISSUE #1358: More complex Example app
**TL;DR: We need your help to build a React app covering all of the styled-components API to help us make sure the library works as expected!**

----

As of #1357 we screenshot integration test [our example app](https://github.com/styled-components/styled-components/tree/master/example) in CI for every PR, which is super awesome to make sure styled-components works as expected. Unfortunately, right now the example app isn't very complex, it's really only a couple lines of code.

We need a bigger Example app which leverages the entire styled-components public API and many CSS edge cases so we know that most things are working as expected. What specific content that app has doesn't really matter, that's all up to you. (massive bonus points if it looks great though!) 

The app lives in the `example/` folder in the repo. Whatever specific content you come up with for the app, it should use all of the following things at least once:

- styled-components API:
  - [ ] `injectGlobal`
  - [ ] `css`
  - [ ] `keyframes` (note: we screenshot the app in ci, so this has to be something that's applied immediately somehow and doesn't change over time?)
  - [ ] `styled.x`
  - [ ] `styled.x.attrs`
  - [ ] `styled(SomeComp)`
  - [ ] `SomeStyledComp.extend`
  - [ ] `SomeStyledComp.withComponent`
    - Theming
    - [ ] `ThemeProvider`
    - [ ] `withTheme`
  - Interpolations
    - [ ] `css` fragments
    - [ ] Static interpolations
    - [ ] Function interpolations with props
    - [ ] Interpolating other components
- CSS features
  - [ ] Media queries
  - [ ] Pseudo-selectors
  - [ ] Nesting
  - [ ] Parent selectors
- whatever else you can come up with!

Given the size of this task and its ambiguity it makes sense to have multiple people tackle this together. A great first step would be to come up with a quick plan for the contents of the app and then start coding! Any ideas?

### PR DESCRIPTION
**Pull request by maxxgl**
Expanding the functionality of the example app to provide more visual testing.

Fixes #1358.

Most of the test components are quite simple, and rely on the `background` property to make it easy to identify at a glance if there any errors. All components should have at least one `mediumseagreen` element, signifying that the basic feature of the component is functioning.

New example app: 
example-test-js-example-page-should-match-screenshot-1-snap

Caveats: 
Due to the test setup, there is an issue that all of the `styled` or `React` references must be in the index file for linting. There are some code indentation liberties taken to make the code print correctly as well.

### CODE REVIEW

**Comment by probablyup** [comment]
Ooh, this actually would be great to pass through something like https://percy.io/ to help prevent regressions between builds. @mxstbr @kitten

**Comment by kitten** [comment]
That pretty awesome! @probablyup Do we still have the screenshot regression tests on the website? Could just reuse that code for now

**Comment by maxxgl** [comment]
@kitten @probablyup I was finally able to get this to pass the tests.

The current Travis [snapshot test](https://github.com/maxxgl/styled-components/blob/1358-improve-example-app/packages/styled-components/integration-test/example.test.js) uses the `google-chrome-beta` binary as set in the Travis config (which I didn't realize at first). Which means that there are potentially quite a few problems when people test this locally, due to either the browser version being used by puppeeter, or the host system's browser quirks (especially font-related).

Honestly, after getting a little frustrated trying to make this pass tests, I'm not sure I would recommend merging this considering the current snapshot strategy.

**Comment by probablyup** [comment]
What we could do instead is set up storybook in the example app and use https://www.chromaticqa.com/ to do the automated visual regression testing. Then we could drop using the chrome binary entirely.

**Comment by probablyup** [comment]
I'm going to co-opt this and implement chromatic :) will make sure you retain authorships on the commits though 👍

**Comment by probablyup** [comment]
Closing in favor of #2589 which rolls up these changes with different end tooling

**Pull request closed without merging**
