### PR TITLE
Updated deps

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amilajack** [comment]
Should the `src/vendor` dir be ignored by eslint?

**Comment by amilajack** [comment]
@mxstbr What default should be used to fix this error?

https://ci.appveyor.com/project/mxstbr/styled-components/build/963#L1420

**Comment by mxstbr** [comment]
> /home/travis/build/styled-components/styled-components/src/models/ThemeProvider.js
>  14:3  error  propType "children" is not required, but has no corresponding defaultProp declaration  react/require-default-props

`children` should actually be required, a `ThemeProvider` without children doesn't make any sense, does it?

**Comment by mxstbr** [comment]
Thanks for this PR btw, this is awesome!

**Comment by mxstbr** [comment]
Wait why'd we never merge this? 😱

**Comment by amilajack** [comment]
I think it would be better to wait until the jest migration has finished. There'll probably be a lot of merge conflicts if we don't

**Comment by mxstbr** [comment]
Good call, as always 👌

**Pull request closed without merging**
