### PR TITLE
Add 'Component based on props' to docs

### PR DESCRIPTION
**Pull request by k15a**
I've added some examples to show how to choose a component based on props.
Relevant: #494 and #393

### CODE REVIEW

**Comment by ericdfields** [comment]
Can you link to your examples? Thank you.

**Comment by k15a** [comment]
https://github.com/k15a/styled-components/blob/353a7c4f8c4abf19b148857b7c47dad5e7499533/docs/tips-and-tricks.md#choosing-a-component-based-on-props

**Comment by ericdfields** [comment]
@mxstbr you're probably right. I suppose the use case for me is I have a styled component Card that could stand on it's own as a `div` or might be in a list of other Cards. To save a component, I could tell the Card that it should be an `li` instead of a `div`, saving me the trouble of managing styles for `li` (no list style, margin, padding, etc).

There's a good counter argument that the Card's single purpose is to be a card, and the `li`'s purpose is to be the list item.

**Comment by k15a** [comment]
I am open to changes or we could leave this out entirely. I think it's something that could be mentioned in the docs because we had some question if this is possible. Maybe we should add something like this to the docs but with a better solution?

**Pull request closed without merging**
