### PR TITLE
Add styled-media-query to libraries

### PR DESCRIPTION
**Pull request by morajabi**
I think it's useful for others using styled-components.

### CODE REVIEW

**Comment by morajabi** [comment]
@k15a I thought it is ordered in stars count. 
I'm moving it to the last but I have a suggestion: Isn't it better to order them in an order for example alphabetic order or whatever like others do? I don't think the order of addition is a good thing for a plugin list. But it is just a suggestion.

**Comment by philpl** [comment]
@morajabi eventually we should probably get rid of this list inside the readme and have something more organised on the website. But it's not our goal to promote all the best projects in order, but just to show some to express to the reader that we have a healthy community of third-party projects

**Comment by morajabi** [comment]
If you wish I can make a separate page or something you say for them. @philpl

**Comment by philpl** [comment]
@morajabi It's still unclear where several pages for the website will go. Maybe we should start a discussion on Spectrum and talk about it, as I haven't designed or thought about pages like the "Wall of Love", "Companies", "Third party projects", and so on yet.

**Comment by morajabi** [comment]
@philpl OK whenever that happened, I'd like to help on that.

**Comment by philpl** [comment]
@morajabi https://spectrum.chat/thread/25aad1ea-4c6d-4558-97a6-3214f47d3287

**Pull request merged**
