### PR TITLE
remove unnecessary ESLint disable comment

### PR DESCRIPTION
**Pull request by ryota-murakami**
Thanks😎

### CODE REVIEW

**Comment by probablyup** [comment]
Can you switch the base branch to be `develop` please?

**Comment by ryota-murakami** [comment]
@probablyup I'm afraid, I'll be resolve conflict.

**Comment by probablyup** [comment]
@ryota-murakami I'll just cherry pick the change in my next PR - thanks!

**Comment by ryota-murakami** [comment]
@probablyup Thanks your handles with kindness!

**Pull request closed without merging**
