### PR TITLE
Add library size check in CI

### PR DESCRIPTION
**Pull request by siddharthkp**
Basically this:

This will help in **keeping** the library tiny.

1. Setting the file and threshold:

    The config sits inside `package.json`, the threshold is set to 9.5kB right now.
You can add multiple files here. ([docs](https://github.com/siddharthkp/bundlesize/blob/master/README.md#configuration))

2. Authorize bundlesize:

    `bundlesize` needs access to github API with scope `repo:status`, You can follow the [steps here](https://github.com/siddharthkp/bundlesize/blob/master/README.md#build-status)

Here's a demo pull request in glamor's fork: https://github.com/siddharthkp/glamor/pull/1

### CODE REVIEW

**Comment by philpl** [comment]
This is AWESOME! :tada:

But maybe we should add it to Danger CI instead and turn it into a warning there? cc @mxstbr

**Comment by siddharthkp** [comment]
@philp, I made bundlesize in a certain way so that you can use it anywhere. However, I'm sure the output can be used with danger as well.

**Comment by mxstbr** [comment]
I like having this as a status check because it's more visible, happy for us to add this!

Wait @siddharthkp you made bundlesize? Can you please please please make HTTPS work so it'll show the image on https://styled-components.com???? 🙏

**Comment by mxstbr** [comment]
Also you should really add a notice to the homepage (`bundlesize.io`) about who made it, that'd make it seem more trustworthy. It's an awesome service!

**Comment by siddharthkp** [comment]
@mxstbr I think you're confusing with badge-size 😄

**Comment by mxstbr** [comment]
Oh, maybe. Isn't that using bundlesize though? Who made badge size?

**Comment by philpl** [comment]
@mxstbr alright, in that case let's merge it :) I thought you'd prefer it in danger

**Comment by siddharthkp** [comment]
> Oh, maybe. Isn't that using bundlesize though? Who made badge size?

Nope, I built `bundlesize` just this week 😋 
I can probably add badges though, I have the data

the badge-size repo is here: https://github.com/ngryman/badge-size

**Comment by siddharthkp** [comment]
@philpl Before you merge, remember to configure it:

- Enable `Build branch updates` and `Build pull request updates` on travis-ci. ([screenshot](https://raw.githubusercontent.com/siddharthkp/bundlesize/master/art/travis.png))
- [Authorize `bundlesize` for status access](https://github.com/login/oauth/authorize?scope=repo%3Astatus&client_id=6756cb03a8d6528aca5a), copy the token provided.
- Add this token as `github_token` as environment parameter in travis settings

(Ask me for help if you're stuck)

**Comment by mxstbr** [comment]
Tried authorizing, got "503 | The deployment is currently unavailable." 😕

**Comment by siddharthkp** [comment]
@mxstbr Sorry about that. `now.sh` freezes deployments after some hours of inactivity. I have fixed that. Instances will stay active now.

**Comment by mxstbr** [comment]
Done, how do we test it?

**Comment by siddharthkp** [comment]
1. The absolute threshold part is already working: [travis logs](https://travis-ci.org/styled-components/styled-components/jobs/248624758#L819)

2. For comparison with master + build status: Merge this PR and create another

**Comment by mxstbr** [comment]
Yessss, thanks @siddharthkp this is great!

**Pull request merged**
