### PR TITLE
Fix theming when theme has been changed using ThemeProvider

### LINKED ISSUE #261: Theme stopped updating
## Version
1.1.2 on React Native

## Expected Behavior
All components that use { theme } update when the theme is changed.

## Actual Behavior
Most of components stopped updating the colors after migrating from v1.1.1 to v1.1.2.

### PR DESCRIPTION
**Pull request by michalkvasnicak**
Fixes #261

### CODE REVIEW

**Comment by michalkvasnicak** [comment]
@mxstbr appveyor didn't pass because order of css properties generated by autoprefixer is reversed.

**Comment by michalkvasnicak** [comment]
Added `className` checks to tests too so it won't happen again.

**Comment by k15a** [comment]
Unfortunately this doesn't work for me (tested with React)

**Comment by michalkvasnicak** [comment]
@k15a can you create an example so I can reproduce this? Because I added the test that reproduced the issue and it's fixed.

**Comment by k15a** [comment]
I will try it.

**Comment by michalkvasnicak** [comment]
If you pass theme as same reference but with changed property it won't update a theme.

```js


```

**Comment by michalkvasnicak** [comment]
I am sorry for reopening, misclicked. :(

**Comment by k15a** [comment]
> If you pass theme as same reference but with changed property it won't update a theme.

Is this the intended behaviour?

**Comment by k15a** [comment]
Reproduction without fix: https://styledtheme-xmbczspacp.now.sh/
Reproduction with fix: https://styledtheme-prtnqsuxfk.now.sh/

You can see the src code if you append `_src` to the url.

**Comment by michalkvasnicak** [comment]
@k15a I am looking at https://styledtheme-prtnqsuxfk.now.sh/_src/?f=package.json and you don't have correct `styled-components`. You need to set it like this:

```json
{
   "dependencies": {
       "styled-components": "git://github.com/michalkvasnicak/styled-components.git#fix/theming"
   }
}
```

**Comment by k15a** [comment]
I've copied the styled-components.js from dist to the src and importing it with '../styled-components.js'. See https://styledtheme-prtnqsuxfk.now.sh/_src/?f=src%2FApp.js. I will upload another one with the `"styled-components": "git://github.com/michalkvasnicak/styled-components.git#fix/theming"`.

**Comment by k15a** [comment]
How can I trigger the styled-components build script if I am using the git url? Otherwise webpack can't find styled-components. Sorry I haven't done this before.

**Comment by michalkvasnicak** [comment]
@k15a I tried your example locally and this bug is still here.

**Comment by michalkvasnicak** [comment]
@mxstbr this is caused by weird race condition. In @k15a example it'll generate css classes for all themes but `componentWillReceiveProps` will rewrite changes made by `setState` from change subscriber.

In examples from above links there is change in `theme`. This will call `setState` in subscriber but it will also trigger re-render so `componentWillReceiveProps` will be called too. Somehow `this.state.theme` in `componentWillReceiveProps` is not new value from subscriber, but previous one (in this case it is always the value from first render).

**Comment by michalkvasnicak** [comment]
If we keep everything as is except `componentWillReceiveProps` and we change it to be like this:

```js
componentWillReceiveProps(nextProps: { theme?: Theme, [key: string]: any }) {
        const theme = nextProps.theme || this.state.theme;

        const generatedClassName = this.generateAndInjectStyles(theme, nextProps)
        this.setState({ generatedClassName })
}
```

it starts to work but first change will be weird because it will use second theme not after first click, but after second click.

**Comment by brunolemos** [comment]
@michalkvasnicak the second argument of `componentWillReceiveProps` is `nextState`, maybe that could help

**Comment by brunolemos** [comment]
Another idea is to use the callback of `this.setState` to prevent the race condition

**Comment by michalkvasnicak** [comment]
@brunolemos second argument is not `nextState` or maybe I am missing something (https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops)

image

I don't see how I can use callback from `this.setState` because we are setting `theme` and `generatedClassName` to `state`. But maybe I am just tired. Do you have some idea?

**Comment by michalkvasnicak** [comment]
Only thing that helped is if we `generateAndInjectStyled` in `render` method. This way we have always the correct state.

Component `willReceiveProps` will work only if `this.props.theme` is set otherwise it won't do anything.

This way it behaves correctly with `ThemeProvider` or without it. But I think we would need to incorporate some memoization to `generateAndInjectStyles`. 

Any ideas?

**Comment by michalkvasnicak** [comment]
Sorry again for reopening, incorrect rebase. Now it should be just fine. Please someone test it with react-native. It works fine with examples from @k15a. Also there is a test case which is testing `ThemeProvider` changes as well as props changes.

**Comment by brunolemos** [comment]
@michalkvasnicak Tested on React Native, it's working 👍  :shipit:

**Comment by brunolemos** [comment]
Yeah, probably, because it's back on render method.

**Comment by michalkvasnicak** [comment]
Maybe there is but I can't find one. If we revert back to 1.1.1 then theming does not work without `ThemeProvider`. 

I don't see how `componentWillReceiveProps` is performance optimization. It is called on every re-render except the one issued by `setState`. So if you are using `ThemeProvider` like the one in examples from @k15a there is `setState` called with `componentWillReceiveProps` too.

**Comment by michalkvasnicak** [comment]
I don't know how #137 has been benchmarked but from what I see there is only speed up in `render` but slow down in `componentWillReceiveProps` so I think this affects reconciliation. But really I don't know :) 

Maybe some memoization would be better, we return current theme if theme or props are not changed.

**Comment by mxstbr** [comment]
Closing in favor of #264 which solves this much more elegantly. Thanks for the effort put into this PR and digging into it @michalkvasnicak!

**Pull request closed without merging**
