### PR TITLE
fix bug where style tag has been removed from the DOM

### PR DESCRIPTION
**Pull request by ryanirilli**
Due to how [rehydrate](https://github.com/styled-components/styled-components/blob/c3eedbeb79621acd668e15ed2d63107528ed81c3/packages/styled-components/src/models/StyleTags.js#L410) works, there is a scenario where the `Tag.styleTag` will be an element that has been removed from the DOM causing styles not to be rendered. 

This is happening for us because there is another javascript bundle being loaded on our page after our style tag has been created with the same version of styled-components. 

This ensures the style tag be added back to the DOM before trying to insertRules to it. There may be a better approach here but this is the simplest fix as far as I can tell.

 I did not see existing tests for `insertRules` or I would have added one.

### CODE REVIEW

**Comment by matthewverde** [comment]
An alternative to this would be to change how the list of elements is grabbed for the rehydration step, or how elements are removed from the DOM during the rehydration step. It seems like removing an element from the DOM when it's parent is the target element (aka the head) should never be done.

**Comment by probablyup** [comment]
I believe there’s another PR up for this also

**Comment by ryanirilli** [comment]
@probablyup do you think this is a reasonable change?

**Comment by ryanirilli** [comment]
Thanks @probablyup, I added a changelog entry.

**Comment by ryanirilli** [comment]
Anything else we need to do to get this merged?

**Comment by kitten** [comment]
@ryanirilli The sheet implementation for canary (v5) will change shortly and Alters how this works.

There's a small issue here in that the original target is not respected. Either way though, thanks for opening this 👍 I'm afraid though that I have some more concerns around merging this 😅

I'm unsure of whether we'll merge this, since it might have a slight impact on performance and predictability. Inserting rules is quite a frequent operation and adding code to basically defeat other libraries is not quite in-scope, in my opinion, but a hack.

It does come up when other versions of SC clash, but that's quite a common issue for which we've got some workarounds, presuming that all duplicate versions of SC are new enough.

I'm general, I don't believe that every library working with the DOM should defend against other libraries aggressively altering elements 😅 we'll have a think and will leave se more comments on this PR.

I'll make sure that we port this over to canary, if we do go ahead with this 👍

**Comment by stonebk** [comment]
> It does come up when other versions of SC clash, but that's quite a common issue for which we've got some workarounds, presuming that all duplicate versions of SC are new enough.

@kitten what are the workarounds? This is currently a huge headache for us since it completely breaks style insertion during development. Our current workaround is a forked implementation of styled-components with this fix implemented.

> I'm general, I don't believe that every library working with the DOM should defend against other libraries aggressively altering elements 😅 we'll have a think and will leave se more comments on this PR.

@ryanirilli can probably speak to this better than I can, but this isn't defending against other libraries, it's defending styled-components against itself. We have two dependencies on the page, both using styled-components on the same version -- styled-components should be aware enough not to clobber it's own style tag.

**Comment by kitten** [comment]
Currently `styled-components` already defends against multiple versions being on one page; It [checks for the correct version attribute](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/StyleSheet.js#L83) so in that case you're bundling two identical versions of `styled-components`?

Unfortunately we can't just readd the style tag and assume that everything is going to continue working correctly, since the removal of them indicates that one version of `styled-components` has rehydrated the styles of the other, which will probably lead to other subtle bugs.

The `canary` version of `styled-components` will defend against this by setting the `SC_ATTR` to `"active"` so that another version doesn't "consume" its styles.

**Comment by ryanirilli** [comment]
@kitten the issue we face is that we have two apps (Webpack bundles) loading on the same page that are using the same version of styled components, thus, causing styled-components to go down the rehydrate path and removes the first style tag from the DOM at the [cleanup step](https://github.com/styled-components/styled-components/blob/c3eedbeb79621acd668e15ed2d63107528ed81c3/packages/styled-components/src/models/StyleTags.js#L422). 

However, the style tag node still exists and styles are being injected into it which led us to this fix. The logic here is, if you're going to keep injecting styles into this tag, it _needs_ to be in the DOM. 

I agree, it feels like a hack, but it is reasonable to make the check or at least throw an error here. See #2254 for other people experiencing this issue. 

Perhaps a better fix would be to mark the style tag as "seen" in `makeStyleTag` with a data attribute and remove that from the list [here](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/StyleSheet.js#L83)

In any case, we just would like to figure out how we can support this and defend against this reasonably. Open to suggestions!

**Comment by probablyup** [comment]
@ryanirilli you should use the CDN version of styled components in this case and set your webpack bundles to use the window alias instead

**Comment by ryanirilli** [comment]
> @ryanirilli you should use the CDN version of styled components in this case and set your webpack bundles to use the window alias instead

We do actually use SSR though, is there a viable option that can support that as well?

**Comment by kitten** [comment]
Ah, there's another solution to this though 👍 you can provide two different SC_ATTR constants for both apps which will cause them to use different attributes for their style tags https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constants.js#L4

**Comment by probablyup** [comment]
Another option is to pin each app to a different patch version of the library, but @kitten's recommendation is better since you then aren't potentially losing out on a bugfix

**Comment by ryanirilli** [comment]
If Thank you @kitten @probablyup this is a great idea, I didn't realize we could define those vars via define plugin. We can definitely try that!

**Comment by probablyup** [comment]
Either option means you're loading duplicate copies of the library though, which is unfortunate. If you use the CDN version for your client side bundles and NPM version for SSR it'll all work fine together (just make sure they're all the same version of s-c.)

**Comment by ryanirilli** [comment]
100% agree, we are are in discussion about a long term solution to shared dependencies like this but we're looking for a short term solution at the moment.

**Comment by kitten** [comment]
@ryanirilli thanks again for bringing this problem to us though! It's been mentioned a lot of times but I'll think about how we can make this less painful in version 5 👍

I'll close this issue for now, but please feel free to reach out with any questions you have here or on Twitter.

By the way, maybe a long term solution would be a shared DLL bundle via we packs DLLPlugin?

**Comment by ryanirilli** [comment]
Thank you! and yes DLL plugin is top of the list at the moment but we haven't explored it fully yet. Thanks again all for your support.

**Comment by ryanirilli** [comment]
@kitten It was discovered that this solution is in the docs [here](https://www.styled-components.com/docs/advanced#avoiding-conflicts-with-thirdparty-styles-and-scripts). 

Perhaps elevating that last paragraph could help. I realize it _is_ uncommon but since people are encountering it, the solution may be more discoverable in another section of the site.

**Comment by brendonco** [comment]
> Ah, there's another solution to this though 👍 you can provide two different SC_ATTR constants for both apps which will cause them to use different attributes for their style tags https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constants.js#L4

How do I set SC_ATTR if I'm not using create react cli?

**Pull request closed without merging**
