### PR TITLE
fix: pin dependencies to exact versions prior to bun migration

### PR DESCRIPTION
**Pull request by quantizor**

### CODE REVIEW

**Comment by dubzzz** [comment]
Is the pinning just for the time of the migration?

Actually pinning tends to imply duplicated dependencies on user's side and thus higher bundle size. For instance if one user pulls `@emotion/unitless` on his own either directly or indirectly there is a huge chance that it might pull `0.8.1` and not `0.8.0` for various reasons (including security). Why would you not allow `0.8.1`? (mostly asking to know the reasons behind that change, I'm not challenging the poetntial need for it)

**Comment by quantizor** [comment]
@dubzzz it's meant to be accompanied by https://github.com/styled-components/styled-components/pull/4243

I'll ship it soon, found a corresponding bug in npm that I was hoping would be fixed soon.

**Comment by dubzzz** [comment]
awesome ❤️

**Comment by dumistoklus** [comment]
@quantizor 

> I'll ship it soon, found a corresponding bug in npm that I was hoping would be fixed soon.
This solution doesn't work for deduplication in yarn 3.2.0.

**Pull request merged**
