### PR TITLE
Create directory for core package WIP

### PR DESCRIPTION
**Pull request by makeupsomething**
🚨  This is a WIP!

Beginning the process of splitting into multiple packages for https://github.com/styled-components/styled-components/issues/588

### CODE REVIEW

**Comment by makeupsomething** [comment]
I think im ok so far. As long as im moving in the right direction! Will work on it more today or tomorrow and start adding tests.

**Comment by mxstbr** [comment]
Awesome

**Comment by makeupsomething** [comment]
Just to update here I haven't disappeared, just got busy, will get back to this later this week 🙏

**Comment by riccardoferretti** [comment]
@makeupsomething I am happy to help if you need anything

**Comment by kitten** [comment]
Sorry, closing this since it's quite our t of date and has been inactive for a while 😟 I suppose we'll coordinate adding a core package when the need arises

**Pull request closed without merging**
