### PR TITLE
Primitives: TextInput support

### PR DESCRIPTION
**Pull request by ktj**
- TextInput support (PR waiting in react-primitives repo)
- Updated react-primitives 0.4.2. to 0.4.3
- made tests run (need help to make them pass)

### CODE REVIEW

**Comment by ktj** [comment]
So this is the error when I run `yarn test:primitives`
```
primitives › should generate inline styles

    expect(received).toEqual(expected)
    
    Expected value to equal:
      [{}, undefined]
    Received:
      [63, undefined]

```

Where should I start looking for errors?

**Comment by mxstbr** [comment]
@mathieudutour

**Comment by ktj** [comment]
The maintainer of react-primitives repo isn't very active (active in github, but not in this repo).
For example PR for fixing touchable in react-native has been open for 2 months now.
Any thoughts on that?
Could it be possible to fork primitives under this organization?

**Comment by mathieudutour** [comment]
I'm not sure your PR will be accepted: https://github.com/lelandrichardson/react-primitives/issues/54

as for the error, I'm sorry I don't remember much of the code

**Pull request closed without merging**
