### PR TITLE
feat: Add styled as named export

### PR DESCRIPTION
**Pull request by JacobLey**
closes https://github.com/styled-components/styled-components/issues/3437

Added to the files listed as inputs [here](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/rollup.config.js)

With exception to:
* standalone - it seems intentional there is only one default export and everything else is attached as a name?
* macro - this seems like a babel-only file, which is swapped for the real `styled-components` at build time?

### CODE REVIEW

**Review by samarmohan — APPROVED** [review]

**Review by samarmohan — CHANGES_REQUESTED** [review]
fix conflicts first

**Comment by JacobLey** [comment]
Fixed merge conflicts

**Review by samarmohan — APPROVED** [review]
nice

**Comment by JacobLey** [comment]
Just a bit, running things like `import('./dist/styled-components.cjs.js').then(x => console.log(x.default.default === x.styled)) // true` locally.
And that worked as expected.

I tried installing the package locally with my current project that was having the related issue and started getting `Invalid hook call. Hooks can only be called inside of the body of a function component` errors. (This is a NextJS project if relevant)

So I tried using the `main` branch and ended up getting the same errors. So I don't think the error is related to my changes, but I don't really have great test proof my changes work as expected (generally speaking my changes are small so I _expect_ them to work, but looking for solid proof)

Is this a known/expected issue? What is best way to test locally?

**Comment by JacobLey** [comment]
Also I see this project is moving more over to typescript, which is great. But looks like that is still for internal usage for now?

So once this is merged I will followup with a PR to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/styled-components to declare the named export

**Comment by samarmohan** [comment]
Your error that you get, `Invalid hook call. Hooks can only be called inside of the body of a function component `, happens a lot. Check your hooks and stuff. That’s not a styled components issue.

**Comment by JacobLey** [comment]
I only get this issue when installing my local version of styled components though. So I suspect I am installing it wrong, what is the proper way to install it locally?

I think the issue stems from styled-components using its own instance of React (which only exists in a locally-installed dev environment) rather than my version of React. So the overlap causes the issue.

**Comment by kitten** [comment]
See comments on original issue. Sorry for closing!

**Pull request closed without merging**
