### PR TITLE
Add flow to Travis script and fix flow errors

### PR DESCRIPTION
**Pull request by relekang**
* Fixes the flow errors that have made it to master.
* Adds `npm run flow` to CI.
* Adds lint-rules from flowtype plugin.

### CODE REVIEW

**Comment by relekang** [comment]
Maybe we should add [eslint-plugin-flowtype#require-valid-file-annotation][]?

[eslint-plugin-flowtype#require-valid-file-annotation]: https://github.com/gajus/eslint-plugin-flowtype#require-valid-file-annotation

**Comment by mxstbr** [comment]
Let's do that, and can you also do as @styled-components-bot says? Thanks!

**Comment by relekang** [comment]
@mxstbr Done. I added a few more lint rules, tried to add the flow equivalent of what was already in the config. e.g. the regular semi rule does not work on type declarations.

**Comment by mxstbr** [comment]
Released as `v1.2.1`! 🎉

**Pull request merged**
