### PR TITLE
Upgrade to enzyme v3

### PR DESCRIPTION
**Pull request by theshortcut**
This upgrades to enzyme v3 and fixes a few `$FlowFixMe` errors in the process.

The enzyme flow type definition comes from https://github.com/flowtype/flow-typed/blob/master/definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js so with an upgrade to `flow-bin` the manual stub could be removed and a `flow-typed install` copy should work.

### CODE REVIEW

**Comment by philpl** [comment]
This is amazing! Thanks a lot already in advance :heart:

It seems that the `yarn.lock` was out of date, or some new dependencies triggered an issue with `@types/node@^6.0.46` and `@types/react-native`. cc @styled-components/typers: Can we get a fix for this in case it's our problem, so this can land? :smile:

**Comment by theshortcut** [comment]
Looks like the enzyme update triggered a chain of dependency updates (Cheerio => parse5 => @type/node). I’ll try and look at the Typescript errors ASAP but if anyone else has insights I’d appreciate it.

**Comment by theshortcut** [comment]
Update: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15960 looks like the issue is due to conflicting definitions in `@types/node` and `@types/react-native`. The node dependency is new in this PR so we should resolve it somehow.

**Comment by theshortcut** [comment]
I've added a postinstall script that removes the react-native global type definitions in favor of node's and the typescript compile and lint pass now. Not ideal but I couldn't find a better way around the issue and react-native's globals should match node's anyway.

**Comment by philpl** [comment]
@theshortcut let’s see if one of the chaps in @styled-components/typers has an idea

Apart from that, I think it’s good to go

cc @mxstbr

**Comment by probablyup** [comment]
@theshortcut would you be able to get this mergeable again? sorry for the delay in getting the PR in!

**Comment by philpl** [comment]
Oh dear, sorry I didn’t realise this was waiting all along. 😅 I really need a “GitHub todo list”

**Comment by theshortcut** [comment]
Yep I’ll get it back up to date ASAP!

**Comment by theshortcut** [comment]
@probablyup @philpl this should be mergeable now.

**Comment by probablyup** [comment]
Awesome! Thank you 🙏

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Pull request merged**
