### PR TITLE
Add react-native-web benchmarks to the repo, run headlessly

### PR DESCRIPTION
**Pull request by mxstbr**
- [x] Copy benchmarks folder
- [x] Make it run
- [x] Add top-level script for it
  - [x] Run all benchmarks headlessly
  - [x] Add `--tracing` arg
  - [x] Make it run against the local version of styled-components
- [x] Add docs on how to run them

### CODE REVIEW

**Comment by mxstbr** [comment]
Latest commit adds a script that runs (curr one of) the benchmarks headlessly in puppeteer. Looks like this:

```
~/projects/github/styled-components/styled-components 
❯ yarn run benchmarks
---Mount deep tree---
21.04 ±06.98 ms
(S/L) 17.13/03.90 ms
```

Does this seem useful @kitten @probablyup?

**Comment by mxstbr** [comment]
Latest commit makes it run all three benchmarks headlessly! 😍 This is what it looks like:

```
Starting headless browser...
Opening benchmark app...
Running benchmarks...

---Mount deep tree---
20.87 ±05.67 ms
(S/L) 17.18/03.68 ms


---Mount wide tree---
27.85 ±02.39 ms
(S/L) 22.52/05.33 ms


---Update dynamic styles---
08.24 ±02.28 ms
(S/L) 06.42/01.81 ms

Done!
```

Note that this is literally just the output of the RNW benchmarks they show in the left sidebar. (literally literally, I do `node.innerText` to get that string :laughing:)

**Comment by mxstbr** [comment]
This is great, except I don't know how to get it to run against the local version of styled-components :cry: Any ideas?

**Comment by probablyup** [comment]
I'm not sure how feasible this is, but it'd be great to output some sort of stack trace. I know Chrome supports outputting performance captures...

**Comment by probablyup** [comment]
Also some more pie-in-the-sky ideas:

- Flamecharts / profiling per jest test (allows us to more easily identify scenarios that introduce slow paths)
- Deopt summaries for the benchmarks

**Comment by probablyup** [comment]
This looks great, excited to start using it!

**Pull request merged**
