### PR TITLE
Add workarounds for more border properties

### PR DESCRIPTION
**Pull request by jacobp100**
Could somebody test this as I don’t have access to RN right now!

### CODE REVIEW

**Comment by MatthieuLemoine** [comment]
@jacobp100 I tried It and it does fix #266. Thanks!

**Comment by mxstbr** [comment]
CI failed?

**Comment by jacobp100** [comment]
I don’t think the CI is due to my changes: it looks like a fix happened to correct the order of browser prefixes.

**Comment by mxstbr** [comment]
Shipping since CI failures are unrelated

**Pull request merged**
