### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by danielbayerlein**
Prevent future edits. Happy New Year @mxstbr! 🎆 🍾

### CODE REVIEW

**Comment by probablyup** [comment]
@danielbayerlein can you remove the `[skip ci]` portion of the commit subject? Travis won't run with it 😆

**Comment by danielbayerlein** [comment]
@probablyup Done 😉

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Comment by danielbayerlein** [comment]
@mxstbr Many thanks for the invitation. 💚

**Pull request merged**
