### PR TITLE
refactor: add a util to grab the webpack nonce magic string

### PR DESCRIPTION
**Pull request by probablyup**
I believe this should be detected and replaced by webpack as intended.

### CODE REVIEW

**Comment by probablyup** [comment]
@johannesnagl can you guys test this when you get a chance?

**Comment by johannesnagl** [comment]
@probablyup thanks! will have a look at it on monday or tuesday!

**Comment by probablyup** [comment]
@johannesnagl /bump

**Comment by johannesnagl** [comment]
@probablyup sorry, did not make it in time because I couldn't build styled-components on my machine (wrong node version, …). will have a second look > August, 21st -> starting my first vacation with baby tomorrow.

**Comment by mxstbr** [comment]
Flow is failing, mind fixing that?

**Comment by probablyup** [comment]
@mxstbr done

**Comment by probablyup** [comment]
@mxstbr I threw together a little project to verify everything works and it appears to 👍  should be good to merge

**Comment by johannesnagl** [comment]
sorry for not actively helping here - we're having a big rewrite which needs to be finished in two weeks. 

Glad @probablyup came up with a project to verify the new code, though! Huge kudos!

**Pull request merged**
