### PR TITLE
Avoid subscribing static components

### PR DESCRIPTION
**Pull request by mxstbr**
I'm not sure if this breaks anything, but if it doesn't it might prevent some unnecessary re-renders?

### CODE REVIEW

**Comment by probablyup** [comment]
This makes sense in theory. Breaks a ton of tests though...

**Comment by mxstbr** [comment]
What the hell are those errors too... 😱

**Comment by mxstbr** [comment]
@kitten why exactly do we do `this.styleSheet = styleSheet` over and over and over every render?

**Comment by probablyup** [comment]
I think it can change in SSR scenarios from first construction to final emit?

**Comment by mxstbr** [comment]
Should probably also do on native btw?

**Comment by probablyup** [comment]
We don't have a concept of "staticness" in native at the moment. I looked 😛

**Pull request merged**
