### PR TITLE
Fix breaking new lines on streaming

### LINKED ISSUE #1478: Some styles are being returned on a new line using streaming
## Version
styled-components: 3.1.5

## Reproduction

I am trying to use the new streaming API. I am using `redux`, `react-router` and `react-loadable`. This is how I have it setup so far on my server file:

```js

    const sheet = new ServerStyleSheet()
    let modules = []

    const stream = sheet.interleaveWithNodeStream(renderToNodeStream(
      sheet.collectStyles(
        <Loadable.Capture report={moduleName => modules.push(moduleName)}>
          <Provider store={store}>
            <StaticRouter
              location={req.url}
              context={context}
              basename={basename}
            >
              <ThemeProvider>
                <App />
              </ThemeProvider>
            </StaticRouter>
          </Provider>
        </Loadable.Capture>
      )
    ))

    stream.pipe(res, { end: false })

    let bundles = getBundles(loadableStats, modules)

    const remainingChunk = html.remainingChunk(
      bundleName,
      bundles
    )
    
    stream.on('end', () => res.end(remainingChunk))
```

client file:
```js
const render = () => {
  consolidateStreamedStyles()
  Loadable.preloadReady().then(() => {
    ReactDOM.hydrate(
      <AppContainer>
        <App />
      </AppContainer>,
      document.getElementById('root')
    )
  })
}

render()

if (module.hot) {
  module.hot.accept('components/App', () => {
    render()
  })
}
```

The streaming seems to work fine except some of the characters are on a new line. Here is how the styles look like on the source view.

```
r
--
  | d
  | e
  | r
  | -
  | b
  | o
  | x
  | ;
  | }
  | /* sc-component-id: sc-keyframes-gPFNxc */
  | @-webkit-keyframes gPFNxc{0%{top:12px;-webkit-transform:scale(0);-ms-transform:scale(0);transform:scale(0);}40%{-webkit-transform:scale(1.0);-ms-transform:scale(1.0);transform:scale(1.0);}50%{top:-12px;}60%{-webkit-transform:scale(1.0);-ms-transform:scale(1.0);transform:scale(1.0);}100%{top:12px;-webkit-transform:scale(0);-ms-transform:scale(0);transform:scale(0);}}
  | @keyframes gPFNxc{0%{top:12px;-webkit-transform:scale(0);-ms-transform:scale(0);transform:scale(0);}40%{-webkit-transform:scale(1.0);-ms-transform:scale(1.0);transform:scale(1.0);}50%{top:-12px;}60%{-webkit-transform:scale(1.0);-ms-transform:scale(1.0);transform:scale(1.0);}100%{top:12px;-webkit-transform:scale(0);-ms-transform:scale(0);transform:scale(0);}}
  | /* sc-component-id: sc-bwzfXH */
  | .sc-bwzfXH {}
  |  
  |  
  | .
  | e
  | U
  | h
  | P
  | Z
  | g
  | {
  | p
  | a
  | d
  | d
  | i
  | n
  | g
  | -
  | l
  | e
  | f
  | t
  | :

```

Any ideas?

### PR DESCRIPTION
**Pull request by hakimelek**
Should fix #1478.

### CODE REVIEW

**Comment by kitten** [comment]
I actually discovered the same thing in the refactor: https://github.com/styled-components/styled-components/pull/1501/files#diff-4ebce830858431daa5d5e4570438264aR284

`comp.css += '\n'`

^ the trailing newline here shouldn't be necessary as the marker (`/* sc-component-id: sc-keyframes-keyframe_0 */`) contains a leading and a trailing one (not sure if this is inconsistent on `master`)

**Comment by hakimelek** [comment]
@kitten Yeah I think it's not really necessary, I actually kept there because I thought the old version was trying to add the new line.

**Comment by kitten** [comment]
@hakimelek I’m just really careful with these things as we accidentally broke the rehydration before 😅

**Comment by kitten** [comment]
Please take a look at this PR now that it’s merged since it should also address this problem. Thank you either way for contributing and feel free to reopen it if it is still relevant. Cheers! 👍😊 https://github.com/styled-components/styled-components/pull/1501

**Pull request closed without merging**
