### PR TITLE
Delete unused src folder.

### PR DESCRIPTION
**Pull request by alansouzati**
I believe the `src` folder needs to be removed now that you moved to monorepo.

### CODE REVIEW

**Comment by mxstbr** [comment]
All old versions of styled-components link to that file when an error happens in production, which is why we left that file where it is. We need to revert this PR.

**Comment by probablyup** [comment]
Ahhhh crap

**Comment by mxstbr** [comment]
No worries, reverted in #2443

**Comment by alansouzati** [comment]
i see. it might be a good idea adding a markdown comment to avoid this to be deleted in the future

**Comment by alansouzati** [comment]
never mind. just saw that you actually added the comment now

**Pull request merged**
