### PR TITLE
Add benchmarking

### PR DESCRIPTION
**Pull request by jacobp100**
See #471

### CODE REVIEW

**Comment by mxstbr** [comment]
Oh wow this is looking awesome! /cc @geelen 

Can we run this in CI with consistent results? Maybe run an empty benchmark (i.e. just calling a `noop` function) a bunch of times to get a baseline for the current CI state, then run the actual benchmark a bunch of times and take the diff from the baseline? I think webpack does something like that, /cc @TheLarkInn

**Comment by jacobp100** [comment]
Benchmark.js should handle consistent results! It’s then mostly about the machine and the load on it. Could try it on the CI and see what happens when we run it a few times?

**Comment by mxstbr** [comment]
> Could try it on the CI and see what happens when we run it a few times?

Let's do that, all you should need to do is add it to `.travis.yml`?

**Comment by mxstbr** [comment]
> Error: Cannot find module "react-test-renderer"

Might want to fix that 😉 Also, Travis fails because Flow complains about all the non-flow-typed files.

**Comment by jacobp100** [comment]
The remaining native tests will be fixed when #406 is merged.

**Comment by mxstbr** [comment]
Going to restart CI a bunch of times to see if we get consistent results for the benchmarking. I'll update this comment as the results happen.

**Run 1**

```
Results for native
0                                  1            
---------------------------------  -------------
simple component                   0.503±0.208ms
prop changes                       1.421±0.868ms
prop shorthands                    0.000±0.000ms
prop shorthands with prop changes  0.000±0.000ms

Results for browser
0                                  1            
---------------------------------  -------------
simple component                   0.430±0.224ms
prop changes                       1.118±0.533ms
prop shorthands                    0.364±0.252ms
prop shorthands with prop changes  0.933±0.446ms
```

**Comment by mxstbr** [comment]
I just had a realisation.

We can use Travis [build artifacts](https://docs.travis-ci.com/user/uploading-artifacts/) to store our benchmarking results as JSON, and then compare the current run to the previous run/output the results nicely human-readable from our `Dangerfile.js`!

**Comment by jacobp100** [comment]
I'm not sure about running this on the CI now 😂 The results vary so much, and they seem to vary way more when you start doing more in the tests! Maybe we could try and find a machine with consistent performance.

**Comment by mxstbr** [comment]
I was expecting that, to be honest—it's not like Travis promises to give you the exact same amount of power every time you run a CI process. That's why I said we should add a baseline!

Let's try benchmarking a noop function (`() => { }`) a bunch of times to get a baseline value to compare against, then reporting the diff between running styled-components and the noop function instead of the raw styled-components values.

In theory, by having a baseline we account for changes in CI power which should give us consistent results. What do you think?

**Comment by jacobp100** [comment]
Oh I'll try that!

**Comment by mxstbr** [comment]
Another note, I think by using the `env` key in `.travis.yml` and running the benchmarks based on the `RUN_BENCHMARKS` env variable being set to true we can run a travis instance _just_ for the benchmarks. (see [the travis docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Build-Matrix) for more info)

That might be helpful?

**Comment by mxstbr** [comment]
## With baseline results

(all of these are on Node 7)

**Run 1**

```
native results                     Time       
---------------------------------  -----------
simple component                   1.181±0.349
prop changes                       3.764±0.444
prop shorthands                    0.000±0.000
prop shorthands with prop changes  0.000±0.000

browser results                    Time       
---------------------------------  -----------
simple component                   1.292±0.386
prop changes                       2.906±0.494
prop shorthands                    1.254±0.363
prop shorthands with prop changes  3.128±0.547
```

**Comment by jacobp100** [comment]
Hmm. It still seems flaky for a few tests. But this probably the best we'll get. Still interested in adding it to the CI? If so, I'll clean up the branch a bit.

untitled 2

**Comment by mxstbr** [comment]
Running on CI, we're getting much closer than before.

Let's try running the _whole thing_ a bunch of times and taking the average of a handful of runs instead of the diff results?

**Comment by jacobp100** [comment]
Benchmark.js does that for us! I think it's just down to the load of the server at the point you begin.

We could go overkill and run the baseline test between each test, but that would take ages (and Travis might not like that).

This graph might highlight the problem tests a bit better...

bar

**Comment by mxstbr** [comment]
> but that would take ages

Not too worried about that if it runs in its own Travis process, since that means it won't block testing, linting etc. from failing fast. Let's try?

**Comment by jacobp100** [comment]
I think it just got worse 😂

bar-2

**Comment by mxstbr** [comment]
Man that's annoying. Okay, last idea then: what about running master and PR in the same process to make them comparable?

**Comment by jacobp100** [comment]
I think the variation is mostly down to variations in the load over time for Travis. Some of the results vary a huge amount, but some seem pretty okay. Perhaps we could just warn people, but also say that it isn't 100% reliable, and that they can re-run the CI if they want to be sure?

**Comment by jacobp100** [comment]
Maybe we could just always print the results for every CI run and compare it with the last one. We'll just use it as vague advice, and let people decide whether it was performance-changing or not.

**Comment by philpl** [comment]
@jacobp100 Since this is in a separate repo now, let's close it and add it once we have lerna, right? :wink:

**Comment by jacobp100** [comment]
Yea that seems like the best option now!

**Pull request closed without merging**
