### PR TITLE
Add name property as possible name for component

### LINKED ISSUE #448: Styled(undefined) in React Developer Tools when wrapping Link component
## Version
2.0.0-1

## Reproduction
http://www.webpackbin.com/EygFtNoDf

## Steps to reproduce
Wrap a `<Link>` component (react-router 4.0.0-alpha.6) as `styled(Link)`.

## Expected Behavior
In React Developer Tools it should be named `Styled(Link)`.

## Actual Behavior
It is named `Styled(undefined)`.

### PR DESCRIPTION
**Pull request by k15a**
Closes #448

### CODE REVIEW

**Comment by k15a** [comment]
Hey @mxstbr,

I am happy to add some tests. Could you say me where the tests for this should be located? Couldn't find a similar test.

**Comment by mxstbr** [comment]
What about `src/test/basic.test.js`? We don't verify this behaviour at all at the moment, it'd be great to get all of it tested!

**Comment by k15a** [comment]
I've added some tests and changed the displayName to `Styled(Component)` instead of `Styled(undefined)`

**Comment by mxstbr** [comment]
Oh wait, we still need a CHANGELOG entry 😊

**Comment by k15a** [comment]
Mhh. That's not really a change because it was this way in v1. But I've written a little changelog entry to make your bot happy 😊

**Comment by mxstbr** [comment]
> That's not really a change because it was this way in v1.

Wait, why do we have to fix this then? Is this already fixed on the `master` branch?

**Comment by k15a** [comment]
Ohh sorry that was my fault. It's unfixed in master.

**Comment by mxstbr** [comment]
Let's fix it on `master` then, and when we merge `master` back into `v2` (_cough_ @xcoderzach) this fix will propagate. That we avoid getting out of sync between the branches :blush:

**Pull request closed without merging**
