### PR TITLE
adding the <Button> of react-native entry point

### PR DESCRIPTION
**Pull request by Ginhing**
Official button component was introduced in react-native@0.37.0

### CODE REVIEW

**Comment by Ginhing** [comment]
@mxstbr Done. Let me know if something was wrong.☺

**Comment by mxstbr** [comment]
Awesome, thanks!

**Comment by mrpatiwi** [comment]
Will be a release coming soon containing this patch? 👍

**Comment by mxstbr** [comment]
Yes, very soon! (want to get #152 in first)

**Pull request merged**
