### PR TITLE
Remove test-results.json from git

### PR DESCRIPTION
**Pull request by mxstbr**
This file is necessary for danger-plugin-jest to work correctly, but there's really no need to check it into git and get conflicts on every single PR.

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by mxstbr** [comment]
Thanks a lot for contributing to styled-components! I've invited you to our organization, if you have any questions, let me know!

**Comment by philpl** [comment]
@mxstbr OH! I previously thought it's required. What a happy surprise that we're able to remove it :smile:

**Comment by mxstbr** [comment]
Same, it was super annoying though haha

**Pull request merged**
