### PR TITLE
styled web components

### PR DESCRIPTION
**Pull request by stephenkingsley**
to add some features in #128 

how to use:

```js
const Title = styled.styledWeb.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`;
Title.textContent = 'hello style-components'
// Create a <Wrapper> react component that renders a <section> with
// some padding and a papayawhip background
const Wrapper = styled.styledWeb.section`
  padding: 4em;
  background: papayawhip;
`;

Wrapper.appendChild(Title);

document.querySelector('#container').appendChild(Wrapper);
```

### CODE REVIEW

**Comment by stephenkingsley** [comment]
because I rebase the master, so had 9 participants here! maybe this is my mistake.

**Comment by stephenkingsley** [comment]
I think it can reviwe first time

**Comment by mxstbr** [comment]
Could you rebase just your changes on top of `master`, so we don't have all the unrelated commits in here? Thank you!

**Comment by stephenkingsley** [comment]
sure, I open another pr, I think this is the most convenient way

**Pull request closed without merging**
