### PR TITLE
Fix resolving react-dom in sandbox

### PR DESCRIPTION
**Pull request by Fer0x**
Fix https://github.com/styled-components/styled-components/issues/2136

### CODE REVIEW

**Comment by probablyup** [comment]
Why is it getting duplicated?

**Comment by probablyup** [comment]
AppVeyor doesn't like this for some reason...

**Comment by Fer0x** [comment]
@probablyup 

> AppVeyor failed to assign job to 'gce' build environment after 3 attempt(s). The envronment is either unavailable or there are no free workers, however alternate build environment was not configured by the system administrator. Please try again later.

I don't think that's problem with PR

**Comment by probablyup** [comment]
Going to merge this to fix it. I think we should probably make sandbox be a yarn workspace though so we can just use the devDep specified at the top level.

**Pull request merged**
