### PR TITLE
updated package.json to allow patches of stylis when installing deps

### PR DESCRIPTION
**Pull request by silverlight513**
There have been multiple patch updates to stylis with fixes for multiple issues. Styled components currently installs 2.0.3. The latest stylis is 2.0.12. 

Examples of a few issues:
https://github.com/thysultan/stylis.js/issues/16
https://github.com/styled-components/styled-components/issues/775

### CODE REVIEW

**Comment by k15a** [comment]
Actually, the `^` already includes patches. The bigger problem is that we bundle stylis with styled-components which locks the version for webpack users. We should probably update our build process before v2 final release.

**Comment by philpl** [comment]
@k15a We should probably add stylis as an external for the `.es.js` build

**Comment by silverlight513** [comment]
Ah okay, fair enough. Would an updated patch version of stylis in the yarn.lock not help webpack users at all?

**Comment by philpl** [comment]
@silverlight513 no, webpack 2 and rollup will point to the ES bundle

**Comment by k15a** [comment]
I think we should create another distribution folder which is compiled without modules.

So webpack and rollup can use this folder and bundle it alone and everyone who wants to include styled-components via script tag can use unpkg.com and use the bundles.

**Comment by silverlight513** [comment]
Oh, I didn't realise that. Shall we close this PR then as it's pointless to the project. Other than discussion about the issue.

**Comment by philpl** [comment]
@k15a don't think that's a good idea. We can just change the `.es.js` module alone, since that's not the UMD bundle that you'd use on script tags, etc.

**Comment by k15a** [comment]
Good point. Is there a way to automatically exclude all dependencies from the `.es.js` bundle?

**Comment by philpl** [comment]
@k15a yea, adding all keys of `dependencies` to `externals`, but that's not a good idea either ^^ It'd probably introduce some quirks over time. I'll open a PR that modifies the ES bundle in a few minutes.

**Comment by k15a** [comment]
Could you explain why this isn't a good idea? I mean webpack and rollup can resolve the dependencies on their own when they are not in the bundle. What's the downside of that?

**Comment by philpl** [comment]
@k15a It just adds a layer of unexpectedness imho. I'd change as little as possible for now, since I don't want any weird surprises after the v2 release ^^

**Pull request closed without merging**
