### PR TITLE
Fix style prop accepts function in native components for v5

### PR DESCRIPTION
**Pull request by tkow**
This PR for v5 branch of style prop bug  fix already v5 Pressable released. More detail https://github.com/styled-components/styled-components/pull/3388.
Review in the way it says. Only difference is to checkout fix/3384_style_function_prop_for_v5 in submodule.

### CODE REVIEW

**Comment by RBrNx** [comment]
Would love to see this get merged as soon as possible as it's quite an annoying issue with what seems to be a fairly simple fix 😅 

@probablyup is it possible to get this merged and released into v5? 🙏

**Comment by tkow** [comment]
@probablyup

If you unfamiliar to React Native and have trouble to maintenance the related  codebase, would you mind inviting me maintainer? I'm familiar with it so, maybe help you for that.

**Comment by probablyup** [comment]
@tkow can you point me to where in the react-native docs the style prop accepts a function? I looked but couldn't find anything consistent. I'd rather not introduce prop patterns that require specific knowledge that something is a styled-component where possible.

**Comment by tkow** [comment]
@probablyup Thank you for a reply. I did it.

**Comment by cam-shaw** [comment]
@probablyup Any chance we can get this merged in?

**Review by probablyup — APPROVED** [review]

**Pull request merged**
