### PR TITLE
[typescript] Add failing material-ui test

### PR DESCRIPTION
**Pull request by NeoLegends**
Hey!

We're using the v1-beta branch of material-ui together with styled-components (to great success, so far). Recently we have been getting typing errors, though. I already contacted the material-ui guys, but we could not track down the bug so far. I think it seems best if we join efforts to get the typings working properly again.

~~~Please see this https://github.com/mui-org/material-ui/pull/8781#issuecomment-349460247 comment and the associated thread for reference.~~~

Issue in material-ui repo: https://github.com/mui-org/material-ui/issues/9838

I'm currently trying to make the typings work and if I succeed, I will submit a PR with updated typings.

### CODE REVIEW

**Comment by philpl** [comment]
cc @styled-components/typers: If this is our fault, then why isn't this line being taken into account? https://github.com/styled-components/styled-components/blob/master/typings/styled-components.d.ts#L57

**Comment by pelotom** [comment]
@philpl 

> cc @styled-components/typers: If this is our fault, then why isn't this line being taken into account? https://github.com/styled-components/styled-components/blob/master/typings/styled-components.d.ts#L57

Why isn't the type

```diff
-<P>(component: React.ComponentClass<P>): ThemedStyledFunction<P, T>;
+<P>(component: React.ComponentType<P>): ThemedStyledFunction<P, T>;
```

? Does `styled-components` specifically forbid the use of stateless components?

**Comment by pelotom** [comment]
Ahh, I see that the next overload does allow for stateless components. But for some reason TypeScript can't merge these two overloads to allow for an argument of type `React.ComponentType<P>`. Is there any reason though they couldn't be combined?

```diff
export interface ThemedBaseStyledInterface<T> extends ThemedStyledComponentFactories<T> {
  <P, TTag extends keyof JSX.IntrinsicElements>(tag: TTag): ThemedStyledFunction<P, T, P & JSX.IntrinsicElements[TTag]>;
  <P, O>(component: StyledComponentClass<P, T, O>): ThemedStyledFunction<P, T, O>;
  <P extends { theme: T; }>(component: React.ComponentClass<P>): ThemedStyledFunction<P, T, WithOptionalTheme<P, T>>;
-  <P>(component: React.ComponentClass<P>): ThemedStyledFunction<P, T>;
-  <P extends { [prop: string]: any; theme?: T; }>(component: React.StatelessComponent<P>): ThemedStyledFunction<P, T, WithOptionalTheme<P, T>>;
+  <P extends { [prop: string]: any; theme?: T; }>(component: React.ComponentType<P>): ThemedStyledFunction<P, T, WithOptionalTheme<P, T>>;
}
```

**Comment by pelotom** [comment]
I filed [an issue with TypeScript](https://github.com/Microsoft/TypeScript/issues/21175) about this, but I'm guessing it's something they will consider hard / out of scope. I think the right solution at least in the short term is to have an overload which explicitly supports a `React.ComponentType<P>` argument.

**Comment by philpl** [comment]
@pelotom I’ve seen our own union type at the top of our typings before. Replacing it might be the key.

Do you mind submitting a PR please? 😬

**Comment by pelotom** [comment]
Submitted a PR: #1427

**Comment by philpl** [comment]
@pelotom let's close this in favour of #1427 then 👍it seems the check there will be sufficient to verify this being resolved

**Pull request closed without merging**
