### PR TITLE
fix self-referential behavior in combo selectors

### PR DESCRIPTION
**Pull request by probablyup**
When a component refers to itself with the ampersand placeholder the behavior today is a bit inconsistent and won't work as intended if your component has dynamic styles.

For example:

```jsx
const Comp = styled.div`
  color: ${p => p.color};

  & + & {
    margin-left: 10px;
  }
`;

<div>
  <Comp color="red">Hello</Comp>
  <Comp color="blue">World</Comp>
</div>

// renders
// <div>
//   <div class="sc-a a">Hello</div>
//   <div class="sc-a b">Hello</div>
// </div>
```

The second instance of `Comp` will not get the `margin-left` because a different className is generated due to the different color prop, and today ampersand refers to the current styling context  className.

It effectively looks like this:

```css
// Comp -> .sc-a
// color: red -> .a
// color: blue -> .b

.sc-a {}
.a { color: red }
.a + .a { margin-left: 10px }
.b { color: blue }
.b + .b { margin-left: 10px }
```

Note how the combo is `.a + .a` and `.b + .b`, so only two adjacent components with the exact same styling props would trigger a match. This is a surprising behavior and makes compositions more troublesome.

The solution is to treat the second `&` as a reference back to the component itself (`.sc-a`), not the style of the component.

Then the styles look like this:

```css
// Comp -> .sc-a
// color: red -> .a
// color: blue -> .b

.sc-a {}
.a { color: red }
.a + .sc-a { margin-left: 10px }
.b { color: blue }
.b + .sc-a { margin-left: 10px }
```

And any `Comp` next to a `Comp` will receive the `margin-left`. Note that the reason the first ampersand isn't also switched to the static component class is that will break style isolation.

[before](https://codesandbox.io/s/xpk25v94rz):

& + & -> .b + .b
&[disabled] { & + & } -> .b[disabled] + .b[disabled]

[after](https://codesandbox.io/s/xomz3rj41q):

& + & -> .b + .sc-a
&[disabled] { & + & } -> .b[disabled] + .sc-a[disabled]

fixes #784

### CODE REVIEW

**Comment by probablyup** [comment]
`styled-components@4.0.0-beta.10-2` if anyone wants to help test. Can also hack on the "after" sandbox in OP

**Comment by imbhargav5** [comment]
Perhaps we can add a test for a combination of `&` & `+`  or something just to be sure.

**Comment by imbhargav5** [comment]
@probablyup Just did

**Comment by probablyup** [comment]
@imbhargav5 done

**Comment by imbhargav5** [comment]
Awesome.

**Comment by probablyup** [comment]
@kitten any issues or tests I should add to the suite?

**Comment by kitten** [comment]
@probablyup looks solid to me; the only thing we could do differently is to actually add it as a stylis middleware, to its selector input transform function.

**Pull request merged**
