### PR TITLE
Remove "exports" entries

### PR DESCRIPTION
**Pull request by SilviaPag95**
Fixes the issue raised in https://github.com/styled-components/styled-components/issues/3800#issuecomment-1453355949

### CODE REVIEW

**Review by probablyup — APPROVED** [review]
Thanks!

**Comment by SilviaPag95** [comment]
@probablyup it seems this fix led to another issue. I use styled components inside a library (with rollup) to export them and after this change (when I upgrade to any version after v6.0.0-beta.12) no styles are applied to any of the styled components. The classnames are properly generated.

**Comment by probablyup** [comment]
I think it's probably a different issue. Do you perhaps have two versions of s-c installed?

**Comment by SilviaPag95** [comment]
I see this when I check for duplication with `$ yarn list --pattern styled-components`

In the repo that uses the library with styled-components:
```
├─ babel-plugin-styled-components@2.1.3
└─ styled-components@5.3.11
```

In the repo that generates the library:

```
├─ babel-plugin-styled-components@2.1.3
├─ styled-components@6.0.0-rc.2-4007
└─ typescript-plugin-styled-components@2.0.0
```

If I try to force a resolution for s-c in the repo that uses the library with styled components I get:

```
```
+-- react-drag-drop-files@2.3.9
| `-- UNMET DEPENDENCY styled-components@^5.3.0
`-- styled-components@6.0.0-rc.2-4007
```

**Comment by probablyup** [comment]
Yup that'd be it. You can also force one version of s-c used via webpack resolve alias if you don't want to mess with dependencies.

**Comment by SilviaPag95** [comment]
Unfortunately even when I add the resolution to the latest 6.0.0-rc.2 version the styles are not being applied at all. I'm at a loss

**Comment by SilviaPag95** [comment]
Turns out this solves the issue: https://github.com/styled-components/styled-components/issues/3269#issuecomment-694562245

**Pull request merged**
