### PR TITLE
Add tests for #2127 bug

### PR DESCRIPTION
**Pull request by Fer0x**
Add tests for both (default and inside StyleSheetManager) situations for check respecting order of styles.

### CODE REVIEW

**Comment by mxstbr** [comment]
I think this ties into #2120 and @kitten's plan to overhaul the StyleSheet infra?

**Comment by kitten** [comment]
Hey, if you don't mind, I'll port this over to the feat/styled-sheet branch on canary once it's merged. It will probably fix this bug 👌

**Comment by Fer0x** [comment]
@kitten sure

**Comment by probablyup** [comment]
@Fer0x can you get this rebased?

**Comment by Fer0x** [comment]
@probablyup done

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.

**Pull request closed without merging**
