### PR TITLE
Replace .npmignore with explicit files list in package.json for v2

### PR DESCRIPTION
**Pull request by YasserKaddour**
Replaces #648

### CODE REVIEW

**Comment by philpl** [comment]
lgtm can you add the contributing.md and the code_of_conduct.md as well, please? :wink:

**Comment by YasserKaddour** [comment]
Done 😃

**Comment by philpl** [comment]
Oh shoot! Just noticed that the typings folder is missing

**Comment by YasserKaddour** [comment]
What typing folder ? `flow-typed` it's there

**Comment by YasserKaddour** [comment]
Ah! on the `master` branch this PR is for `v2`, I will do another one for `master`.

**Comment by wtgtybhertgeghgtwtg** [comment]
> Oh shoot! Just noticed that the typings folder is missing

If you mean the `flow-typed` folder, shouldn't it be?  It doesn't do any good to be published.

**Pull request merged**
