### PR TITLE
Add ref documentation for React.createRef()

### PR DESCRIPTION
**Pull request by julmot**

### CODE REVIEW

**Comment by probablyup** [comment]
@julmot Thanks for the PR, mind actually moving this over to https://github.com/styled-components/styled-components-website?

**Comment by julmot** [comment]
@probablyup Sure: https://github.com/styled-components/styled-components-website/pull/267

I'd still merge this since sometimes you find these files on GH in Google too.

**Comment by probablyup** [comment]
Fair point, thanks :)

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Comment by postrad** [comment]
@mxstbr when would we see useful details like this on https://www.styled-components.com/docs? I've found that the docs are really scattered, which can make it hard not only to reference but to share with my team. Thanks!

**Comment by jmiazga** [comment]
@postrad are you looking for the refs docs? they can be found here: https://www.styled-components.com/docs/advanced#refs

**Pull request merged**
