### PR TITLE
Remove dependencies from es bundle

### LINKED ISSUE #438: Module uses bundled code for building with webpack
## Version
2.0

## Steps to reproduce
* Install SC, use webpack to bundle

## Expected Behavior
* Webpack uses `dependencies` for bundling, including some deps that may occur elsewhere in the project

## Actual Behavior
* Webpack includes the rollup .es.js file which bundles everything

In the package.json, `main` is set to `lib/index.js` which is the ES5 modular transpilation. `jsnext:main` is `dist/styled-components.es.js` which is a pre-bundled version that only excludes React. There is also a `module` key set to the same bundle.

I think that `jsnext:main` and `module` should also point to `lib/index.js`, or else the es bundle should exclude regular `dependencies` as well as `peerDependencies`.

### PR DESCRIPTION
**Pull request by k15a**
Fixes #438

### CODE REVIEW

**Comment by mxstbr** [comment]
Hmm, CI already fails?

**Comment by k15a** [comment]
Yes, I forgot that react is installed as a development dependency.

**Comment by mxstbr** [comment]
Can you post a diff of the `.es.js` bundle?

**Comment by k15a** [comment]
https://www.diffchecker.com/1H5rkQGt

**Comment by mxstbr** [comment]
Okay, that looks pretty good! Does this work if `npm linked` into a project that uses the `.es.js` bundle?

**Comment by k15a** [comment]
It's loading the modules from node_modules so it's working.

screen shot 2017-07-01 at 19 27 11

**Comment by mxstbr** [comment]
Nice, this looks good to me then! Let's wait for @Rich-Harris to (hopefully) chime in, otherwise I say we try and ship a pre-release with this? /cc @geelen

**Comment by Rich-Harris** [comment]
Yep, makes total sense if it's likely that those dependencies will be shared by other packages — bundling external deps makes the most sense when you're creating a UMD build for the browser.

FYI in more recent versions of Rollup you can import package.json:

```diff
-// We need to use require here because import creates a parse error
-const pkg = require('./package.json')
+import pkg from './package.json'
```

**Comment by k15a** [comment]
Do we still need rollup-plugin-json if rollup can handle JSON files now? Or is this only for the config?

**Comment by Rich-Harris** [comment]
> Or is this only for the config?

yep, only for the config

**Comment by k15a** [comment]
Should we update Rollup and refactor the import statement before that?

**Comment by philpl** [comment]
@k15a it'd be nice to upgrade rollup as well, if it's not too much trouble :) otherwise we can do that in another PR. Up to you 👍

**Pull request merged**
