### PR TITLE
add ImageBackground typings for update react-native 0.50

### PR DESCRIPTION
**Pull request by mkasten**

### CODE REVIEW

**Comment by philpl** [comment]
cc @styled-components/typers 

@mkasten Thanks for the contribution! It looks like the react-native typings will need updating: https://travis-ci.org/styled-components/styled-components/jobs/298992746

**Comment by Igorbek** [comment]
`Navigator` component was deprecated in react native, we need to remove it.

**Comment by probablyup** [comment]
I think Navigator was removed in v3?

**Comment by kitten** [comment]
@probablyup this was already addressed before. I’m not sure though why the ImageBackground type is gone

**Pull request merged**
