### PR TITLE
Test compat libs

### PR DESCRIPTION
**Pull request by bkazi**
Aim to implement #216 

Alias React using [`moduleNameMapper`](https://facebook.github.io/jest/docs/en/configuration.html#modulenamemapper-object-string-string)
Tried porting [native/primitive tests](https://github.com/styled-components/styled-components/issues/216#issuecomment-325725186) with a simple find and replace of `View` to `div` as a start. Results in failing 14 tests and passing 2 tests
Running the web tests with aliased `preact-compat` results in 3 test suites failing
- basic > jsdom
- theming
- ssr

(currently only working on using preact-compat)

### CODE REVIEW

**Comment by mxstbr** [comment]
The web styles are probably the way to go since the native styles expect the `style` prop to be set which won't be set in Preact.

**Comment by bkazi** [comment]
Ahh that makes more sense now.
Are there specific test suites I should target or just aim to pass all the tests in the test folder?
(sorry it's my first contribution so I'm a bit confused)

**Comment by mxstbr** [comment]
Everything apart from SSR should pass I think? I dunno if theming works in Preact.

**Comment by bkazi** [comment]
The reason for `basic > jsdom` tests failing is that the innerRef function never gets called
and `theming` fails because the props are not updated when trying to update the theme

**Comment by mxstbr** [comment]
For one, maybe `ref`s aren't a thing with Preact? Same with context for theming? I've never used Preact so I'm unsure where the differences with React are, those might be it?

**Comment by philpl** [comment]
@mxstbr `ref`s were added to preact-compat in v4 (?) I believe, and the context is supported as well. The only notable difference is that `children` are sometimes handled quite differently, which we probably won't have to deal with in our tests, I'd imagine

**Comment by bkazi** [comment]
Yeah preact-compat should have feature parity with React

The issue was with Jest not aliasing React and React-DOM all the way in Enzyme
Used a transformer that uses [babel-plugin-module-alias](https://www.npmjs.com/package/babel-plugin-module-alias) as an option to [babel-jest](https://www.npmjs.com/package/babel-jest)
Results in all tests passing for preact-compat, I'll start work on inferno-compat soon.

**Comment by bkazi** [comment]
Actually no
I messed up big time
I wanted to know for sure if the aliasing was working and turns out it only passes because of jest caching and isn't really being aliased
So currently this is a false positive 

I am however working on a fix using [preact-compat-enzyme](https://github.com/windyGex/preact-compat-enzyme) which seems to be the recommended way to go until enzyme v3 which will allow for easier Preact support (reference: developit/preact-compat#82)

**Comment by mxstbr** [comment]
Good catch!

**Comment by mxstbr** [comment]
Any news here? enzyme v3 was released yesterday... :wink:

**Comment by bkazi** [comment]
Yess testing preact with v2 and the above stated libraries proved to be really difficult since there's no shallow renderer support
There is an ongoing adapter implementation for enzyme v3 and preact [preact-enzyme-adapter](https://github.com/aweary/preact-enzyme-adapater), so I'm waiting on progress there
In the meantime it might be worth upgrading the project to enzyme v3

**Comment by mxstbr** [comment]
Is this ever going to be able to be done @bkazi? :cry: Or did the enzyme v3 update just totally fuck us over?

**Comment by kitten** [comment]
Closing due to inactivity, sorry 😖 I also anticipate that a couple of things will change in canary and our hooks implementation will likely not be compatible anymore with a lot of React-like libraries

**Pull request closed without merging**
