### PR TITLE
Fix flow ci config and use default flow supressor

### PR DESCRIPTION
**Pull request by relekang**
This fixes an issue where `npm run flow` always exited with `0` and thus the CI job never failed. It fixes a few errors that had sneaked in by ignoring react-native source and upgrading libdefs.

Furthermore, it changes the suppressor comment to `// $FlowFixMe` which is the default. This will make it easier for users to adopt flowtype. (Based on [tip on twitter](https://twitter.com/flowtype/status/813119893969240069))

cc @styled-components/typers

### CODE REVIEW

**Comment by ryyppy** [comment]
I like it :-) ... what's happening with CI tho?

**Comment by relekang** [comment]
What do you mean? Last commit is green. 🙂

**Comment by mxstbr** [comment]
Awesome, thanks!!

**Comment by Augustin82** [comment]
@ryyppy 
Like I asked in issue #302, are you sure this fixes the problems mentioned there? When can we expect to see this PR in a release?

Many thanks.

**Comment by ryyppy** [comment]
I just tried the current commit on your example project,.. unfortunately the error still persists

**Comment by Augustin82** [comment]
@ryyppy 
Thanks for trying! Shouldn't the issue be reopened, then? Clearly there's something wrong, with a basic clean styled-components install causing flow errors for the user project (thus technically preventing CI and flow gen-files and other stuff).

**Comment by ryyppy** [comment]
@relekang I believe there is something wrong in general, since `import styled from 'styled-components` does not export anything relevant... I would really really like to see a libdef on `flow-typed` as a fix

**Pull request merged**
