### PR TITLE
Expose flow types & add detailed usage docs

### PR DESCRIPTION
**Pull request by ryyppy**
This commit introduces a few flow-related things (and also some misc
stuff):

* Fix some typing errors with glamor / nameGenerator
* Move adapted `flow-typed/npm` libdefs to `flow-typed`
* Add some flow related ignore rules for eslintrc / flowconfig etc.
* Add a `build:flow` script and add it to the build step
* Add docs for making `styled-components` and `flow` work for the consumer

MISC:
* Add test for generateAlphabeticName

As soon as this feature is merged, there will be `flow.js` files
vendored along with transpiled `lib` files on every build.

Related issues: #177 and #151

### CODE REVIEW

**Comment by relekang** [comment]
The flow files generated by build:flow contains regular javascript, but as far as I understand from [the flowtype docs](https://flowtype.org/docs/declarations.html#declaration-files) it should contain declarations similar to the libdefs in the flow-typed folder?

**Comment by ryyppy** [comment]
@relekang Shadow files can also contain implementing code... that's the whole point why they wanted to introduce the `flow gen-flow-files` command... to strip out the implementation code and make the delivery size much more efficient... you can imagine it like this... code located in `lib` is transpiled source without any annotations... if flow sees a `[file].js.flow`, it will parse this code instead... this has nothing to do with libdef syntax

**Comment by ryyppy** [comment]
@mxstbr @geelen @relekang ... Everything done on my side... I even made it Windows compatible ... time to >ship it< 🚀

**Comment by relekang** [comment]
> Shadow files can also contain implementing code... that's the whole point why they wanted to introduce the flow gen-flow-files command... to strip out the implementation code and make the delivery size much more efficient... you can imagine it like this... code located in lib is transpiled source without any annotations... if flow sees a [file].js.flow, it will parse this code instead... this has nothing to do with libdef syntax

Ah, okay 😊

Great job :v:

**Comment by relekang** [comment]
This looks good to me. Tested it on a few projects of mine it works great except there seems to be some problems with the ThemeProvider typings, but I guess it would be better to fix that outside this PR as it is not related to the bundling of flow types. 🙂

**Comment by ryyppy** [comment]
@relekang That's most likely because you use a different flow version... I am 80% sure :-) ... yep we can do that

**Comment by relekang** [comment]
> That's most likely because you use a different flow version

Yeah, it was 0.33.0. Sorry about that.

**Pull request merged**
