### PR TITLE
Fix default props when extending styled components

### PR DESCRIPTION
**Pull request by diegohaz**
WIP

Reference: #88

### CODE REVIEW

**Comment by mxstbr** [comment]
Can I tell you that you're one of the best contributors I've ever seen? Provides both a reproduction and a failing test – 👏👏👏 – I'm a fan.

Are you looking into fixing this? I think the correct way would be to use the check if it's a previous styled component and then doing `class StyledComponent extends PreviousStyledComponent` – but I'm not 100% sure if that works.

**Comment by diegohaz** [comment]
I think the problem is [this line](https://github.com/styled-components/styled-components/blob/96d6bd547a8a9cd83b215736b1470a3bb0af4d22/src/models/StyledComponent.js#L19). When you create `StyledComponent` passing the `target.target` of the parent styled component, it looses other properties.

**Comment by mxstbr** [comment]
Yeah exactly. I think instead of doing that, we should do 

```JS
let Extended
if (isStyledComponent) {
  Extended = target
} else {
  Extended = React.Component
}

class StyledComponent extends Extended {
  // etc.
}
```

or something like that maybe?

**Comment by geelen** [comment]
Gotta merge those `RuleSet`s tho

**Comment by diegohaz** [comment]
The `Extended` solution makes other tests to fail. :(

I managed to make it work in a simple way, but I'm not very used to these typings so maybe it needs some review.

**Comment by diegohaz** [comment]
Yeah, I've tried to do that way, but I think I would need to understand better the whole program flow.

First, I've updated the StyledComponent.js file to this, but all "extending" tests fail, even the one I'm trying to fix:
```js
// @flow
import { Component, createElement, PropTypes } from 'react'

import validAttr from '../utils/validAttr'
import { CHANNEL } from './ThemeProvider'

import type { RuleSet, Target } from '../types'

export default (ComponentStyle: any) => {
  const createStyledComponent = (target: Target, rules: RuleSet, parent?: Target) => {
    const Extended = parent || Component
    /* eslint-disable react/prefer-stateless-function */
    class AbstractStyledComponent extends Extended {
      static isPrototypeOf: Function
      state: any
    }

    /* Handle styled(OtherStyledComponent) differently */
    const isStyledComponent = AbstractStyledComponent.isPrototypeOf(target)
    if (isStyledComponent) {
      return createStyledComponent(target.target, target.rules.concat(rules), target)
    }

    const isTag = typeof target === 'string'
    const componentStyle = new ComponentStyle(rules)

    class StyledComponent extends AbstractStyledComponent {
      static rules: RuleSet
      static target: Target
      state: {
        theme: any,
      }
      unsubscribe: Function

      constructor() {
        super()
        this.state = {
          theme: null,
        }
      }

      componentWillMount() {
        // If there is a theme in the context, subscribe to the event emitter. This
        // is necessary due to pure components blocking context updates, this circumvents
        // that by updating when an event is emitted
        if (this.context[CHANNEL]) {
          const subscribe = this.context[CHANNEL]
          this.unsubscribe = subscribe(theme => {
            // This will be called once immediately
            this.setState({ theme })
          })
        }
      }

      componentWillUnmount() {
        if (this.unsubscribe) {
          this.unsubscribe()
        }
      }

      /* eslint-disable react/prop-types */
      render() {
        const { className, children } = this.props
        const theme = this.state.theme || {}
        const executionContext = Object.assign({}, this.props, { theme })

        const generatedClassName = componentStyle.generateAndInjectStyles(executionContext)
        const propsForElement = {}
        /* Don't pass through non HTML tags through to HTML elements */
        Object.keys(this.props)
          .filter(propName => !isTag || validAttr(propName))
          .forEach(propName => {
            propsForElement[propName] = this.props[propName]
          })
        propsForElement.className = [className, generatedClassName].filter(x => x).join(' ')

        return createElement(target, propsForElement, children)
      }
    }

    /* Used for inheritance */
    StyledComponent.rules = rules
    StyledComponent.target = target

    StyledComponent.displayName = isTag ? `styled.${target}` : `Styled(${target.displayName})`
    StyledComponent.contextTypes = {
      [CHANNEL]: PropTypes.func,
    }
    return StyledComponent
  }

  return createStyledComponent
}
```

The test output is:
```
1) e2e extending should generate a single class if only parent has styles:

      Error: Expected '.a { color: blue; } .b { }' to equal '.a { color: blue; }'
      + expected - actual

      -.a { color: blue; } .b { }
      +.a { color: blue; }

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (src/test/e2e.test.js:178:61)

  2) e2e extending should generate a single class if only child has styles:

      Error: Expected '.a { color: blue; } .b { }' to equal '.a { color: blue; }'
      + expected - actual

      -.a { color: blue; } .b { }
      +.a { color: blue; }

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (src/test/e2e.test.js:188:61)

  3) e2e extending should generate a class for the child with the rules of the parent:

      Error: Expected '.a { color: red; }' to equal '.a { color: blue;color: red; }'
      + expected - actual

      -.a { color: red; }
      +.a { color: blue;color: red; }

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (src/test/e2e.test.js:197:61)

  4) e2e extending should generate different classes for both parent and child:

      Error: Expected '.a { color: blue; } .b { color: red; }' to equal '.a { color: blue; } .b { color: blue;color: red; }'
      + expected - actual

      -.a { color: blue; } .b { color: red; }
      +.a { color: blue; } .b { color: blue;color: red; }

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (src/test/e2e.test.js:207:61)

  5) e2e extending should copy nested rules to the child:

      Error: Expected '.a { color: blue; } .a > h1 { font-size: 4rem; } .b { color: red; }' to equal '.a { color: blue; } .a > h1 { font-size: 4rem; } .b { color: blue; color: red; } .b > h1 { font-size: 4rem; }'
      + expected - actual

      -.a { color: blue; } .a > h1 { font-size: 4rem; } .b { color: red; }
      +.a { color: blue; } .a > h1 { font-size: 4rem; } .b { color: blue; color: red; } .b > h1 { font-size: 4rem; }

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (src/test/e2e.test.js:220:61)

  6) e2e extending should keep default props from parent:

      Error: Expected '.a { color: red; } .b { background-color: green; }' to equal '.a { color: red; } .b { color: red; background-color: green; }'
      + expected - actual

      -.a { color: red; } .b { background-color: green; }
      +.a { color: red; } .b { color: red; background-color: green; }

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (src/test/e2e.test.js:241:61)
```

Do you have any idea?

**Comment by diegohaz** [comment]
Actually, I think I figured it out.

**Comment by mxstbr** [comment]
I was just about to take this, but if you figured it out feel free to push!

**Comment by geelen** [comment]
@diegohaz you hero!!

**Pull request merged**
