### PR TITLE
Added react-native-extended-stylesheet

### LINKED ISSUE #203: Support media queries with React Native
Thanks for the fantastic project guys, I am primarily targeting RN and I though it would be awesome if styled components could provide support for media queries seamlessly in RN.

Turns out that there is a new very promising project to add media queries support to both React and React Native.
> https://github.com/tuckerconnelly/uranium

It would be pretty neat if a bridge would exist to embed this functionality so that I dont have to wrap my style component (which is already a wrapper) with Uranium wrapper.

### PR DESCRIPTION
**Pull request by shripadk**
* Supports REM/Percent units
* Supports Media Queries (Fixes #203)

### CODE REVIEW

**Comment by jacobp100** [comment]
I’m sort of hesitant about picking one of these libraries, as there’s no defacto standard yet. Bounced an idea off in #504 (which uses some of the changes here)

**Comment by philpl** [comment]
@mxstbr @jacobp100 I'll assign this to v3 for now. Are we still interested in adding these features?

**Comment by jacobp100** [comment]
I don't think we'll merge this pr, but we could discuss how we could get this functionality through other ways.

**Comment by aaronschubert0** [comment]
Support for rem/px specifically would be great, so that there's more portability across native and web.

**Comment by jacobp100** [comment]
@aaronschubert0 that would be in css-to-react-native. We have `px` in v2, but no `rem` support as of yet.

**Comment by aaronschubert0** [comment]
@jacobp100 That's awesome, any word on when styled-components will update to v2 of css-to-react-native?

**Comment by jacobp100** [comment]
In styled-components v2—there's a beta if you want to try it now!

**Comment by mxstbr** [comment]
I'm going to close this PR as it's unlikely we'll merge this into core seeing as nobody has asked for this feature.

Thanks for taking the time to make your case!

**Comment by beblaawy** [comment]
@mxstbr I really need this feature! we are working on a base code for both web and mobile and we use RN components as a shared package between them .. and we need media queries for web styling, would you plz add this feature / merge this PR ?

**Pull request closed without merging**
