### PR TITLE
Add SSR PropTypes

### PR DESCRIPTION
**Pull request by digital-flowers**
Add support for PropType ServerStyleSheet in both StyleSheetManager and StyledComponent

### CODE REVIEW

**Comment by philpl** [comment]
cc @geelen @schwers @mxstbr: Should fix our remaining prop types warnings, I believe

LGTM 👍

**Comment by mxstbr** [comment]
Bundle size is failing here?! /cc @siddharthkp what's up with that?

**Comment by siddharthkp** [comment]
It's not bundlesize 😄 

```
Failing the build, there is 1 fail.
## Failures
Please include a CHANGELOG entry. You can find it at <a href='https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md'>CHANGELOG.md</a>
```

bundlesize is warning you that you don't have the [status api enabled](https://github.com/siddharthkp/bundlesize#2-build-status)!

**Comment by mxstbr** [comment]
Oh yeah sorry, totally my bad 🙈 @digital-flowers can you add a CHANGELOG entry please? Then we'll ship this.

**Comment by digital-flowers** [comment]
sorry for delay, is this enough ?

**Comment by damassi** [comment]
Just confirming -- this PR addresses this issue, correct? https://github.com/styled-components/styled-components/pull/1245

**Pull request merged**
