### PR TITLE
Added useTheme hook

### PR DESCRIPTION
**Pull request by semoal**
Added a simple hook to recover theme context easily

### CODE REVIEW

**Comment by kachkaev** [comment]
Related: https://github.com/styled-components/styled-components/issues/2340

**Comment by probablyup** [comment]
Seems fine to me, though perhaps unnecessary since we expose `ThemeContext` already

**Comment by lcswillems** [comment]
I don't think it is unnecessary. It makes import easier.

For example, in Next.js, there is a `useRouter` hook. They could have not included it in Next.js and just let people import `RouterContext` but it makes more annoying to import it.

A lot of libraries add this little hook to make context easier to import. I think it would make sense to do it in styled components.

Thank you for all your work!

**Comment by lcswillems** [comment]
I don't think it is unnecessary since it makes imports easier.

Thank you for all your great work!

**Comment by mxstbr** [comment]
I think this is a perfectly fine API addition, let's :shipit:!

**Pull request merged**
