### PR TITLE
Fix incorrect element output being created by StyleTags

### LINKED ISSUE #1579: Some characters are broken in SSR @ 3.2.0
## Version
styled-components: 3.2.0
babel-plugin-styled-components: 1.5.1

## Reproduction
3.1.6 -> 3.2.0 seems to break some characters. In my case, the single quote is the biggest nuisance. Might be a stylis issue?

## Steps to reproduce
1. Create some styles with single quotes.
```injectGlobal`@import url('https://fonts.googleapis.com/css?family=Roboto')` ```
1. Server side render it

## Expected Behavior
This should be server side rendered:
`@import url('https://fonts.googleapis.com/css?family=Roboto');`

## Actual Behavior
Quotes come out escaped from `ServerStyleSheet.collectStyles()`, like this:
`@import url(\'https://fonts.googleapis.com/css?family=Roboto\');`

After a run through webpack, this is server side rendered:
`@import url(&#x27;https://fonts.googleapis.com/css?family=Roboto&#x27;);`

### PR DESCRIPTION
**Pull request by kitten**
Fixes #1579

### CODE REVIEW

**Comment by kitten** [comment]
@probablyup updated the snapshots and added some dumb invariants that'll stop this from happening again 😅

**Comment by probablyup** [comment]
Can we add a test that contains one of the characters in question?

**Comment by kitten** [comment]
@probablyup I originally did and was very confused, because it turns out that enzyme / the test renderer / dunno doesn't apply the same url encoding that React does

**Comment by jowy** [comment]
3.2.1 soon? 🍻

**Comment by kitten** [comment]
@jowy yep, pending #1577

**Pull request merged**
