### PR TITLE
Refactor sandbox setup

### PR DESCRIPTION
**Pull request by gribnoysup**
Refactored styled-components sandbox to use `micro(-dev)` + `webpack-dev-middleware` + `webpack-hot-loader` as @philpl suggested in https://github.com/styled-components/styled-components/pull/1257#issuecomment-351054607

The new setup is a simplified, dev-only version of the example repo.

What is supported:

- Server-side rendering
- Hot module replacement 🆕 
- Server live-reload 🆕 

The things that aren't working that nice:

- `react-hot-loader` seems to have some problems with detecting how to update styled-components, every SC component produces [this error](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#react-hot-loader-this-component-is-not-accepted-by-hot-loader) during update
- `eslint-loader` still finds some indentation errors in the styled-components src and if the error is emitted by the loader, HMR is not working, so `eslint-loader` is disabled for now

I also changed how examples are loaded: all `*.example.js` files will be loaded as raw strings that could be used to put into `react-live`. That way we can still have examples in js file with formatting and everything, but now we can load them easily into the sandbox without creating some template strings  manually

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
Just to let you know, I've also tested this locally, and I echo what @mxstbr say. Been rebasing the integration tests on this branch, working good so far :+1:

**Comment by probablyup** [comment]
@gribnoysup try https://github.com/quangbuule/extract-hoc

**Comment by gribnoysup** [comment]
@mxstbr yep, totally forgot about logs, will reduce them!

@probablyup thanks for advice! I probably will try this in another PR, don't want to delay the merge and `react-hot-loader` doesn't seems to be a blocker

@philpl I'd appreciate some nits anyway for educational purposes 😸 Will rebase asap

**Comment by gribnoysup** [comment]
@philpl rebasing dismissed the review somehow, sorry!

Rebased on master with a few other changes:

- Disabled `webpackDevMiddleware` logs as @mxstbr suggested
- Added source maps to the client build, somehow I totally forgot about this before 😅
- Changed error handling a little, now errors are properly propagated to the client

Please note that sandbox is not working properly after the rebase because there seems to be an error in the current master branch, that breaks styled-components usage on server (I created another PR with a fix for this https://github.com/styled-components/styled-components/pull/1394)

**Comment by philpl** [comment]
Let's wait for @mxstbr to have a look at your small changes 👍

**Comment by mxstbr** [comment]
Since #1394 was merged (fast PR @gribnoysup! :clap: ) do you mind rebasing on top of master to make sure SSR works again? Then I'll test it locally one last time and we can ship it 👌

**Comment by gribnoysup** [comment]
@mxstbr done 😉

**Comment by mxstbr** [comment]
I'm very very excited about this. Awesome work @gribnoysup!

**Comment by GGAlanSmithee** [comment]
Good work @gribnoysup I'll try to get the examples / integration tests rebased on this

**Pull request merged**
